### ISSUE TITLE
module-oracle: implement non-blocking I/O for SQL commands

### ISSUE THREAD

**Issue by davidnich** [qorelanguage/qore#1010]
there are cases when the server-side execution basically hangs indefinitely, which causes the client side to also hang - in such cases a timeout would allow the client to continue by closing the connection and throwing an appropriate exception

currently sessions have to be killed by the DBA, or in the other case, the client-side Qore process has to be killed, which is not good in a multithreaded server application, since the entire server must be killed in such cases

**Comment by tethal** [comment]
Long running queries can be interrupted using OCIBreak. In non-blocking mode (OCI_ATTR_NONBLOCKING_MODE), the OCIStmtExecute returns immediately with OCI_STILL_EXECUTING and needs to be polled until it fails or succeeds or until the timeout expires in which case the application calls OCIBreak followed by OCIReset and can proceed to execute other queries. In blocking mode, the OCIStmtExecute() call does not return until the statement is executed, but the application can call OCIBreak from another thread in which case the OCIStmtExecute function returns ORA-01013: user requested cancel of current operation. OCIReset does not need to be called in blocking mode.

However, all this applies to execution of queries that take long to process under normal conditions. The OCIBreak call does not "wakeup" the sleeping client thread, it just sends a packet to the server. In a simulated situation where the communication between client and server was disrupted by postponing the response to OCIStmtExecute, calling OCIBreak did not help at all.
