### ISSUE TITLE
implement lazy evaluation for nested functional and list processing operators

### ISSUE THREAD

**Issue by davidnich** [qorelanguage/qore#1025]
instead of passing lists, so that the functions are applied in-line - ex:

``` Perl
fold $1 + "," + $2, (map $1.value, get_iterator(x));
```

currently the `map` expression `map $1.value, get_iterator(x))` is executed and returns a list, which is used as the list argument for the `foldl` operator expression.

Instead in this case, the `foldl` expression should set a parse flag on the list/iterator expression which will allow it to return an iterator object instead of a list, which will allow the `foldl` expression to operate directly on the results of the `map` expression.

**Comment by davidnich** [comment]
@tethal that pull request was just related to this, but did not implement it, sorry for not being clear

**Comment by tethal** [comment]
you were clear, I did not close this - must have been closed automatically when I merged the pull request

**Comment by davidnich** [comment]
ok no worries, also not urgent - would be cool to have for 0.8.13, because with this change we would have basically real functional operators with lazy evaluation, let's discuss later (streams are definitely higher priority)
