### ISSUE TITLE
cmake does not support building module documentation

### ISSUE THREAD

**Issue by davidnich** [qorelanguage/qore#1027]
cmake output:

```
CMake Warning at cmake/QoreMacros.cmake:189 (message):
  Doxygen support for user modules is still TODO
Call Stack (most recent call first):
  CMakeLists.txt:664 (qore_user_modules)
```

**Comment by pvanek** [comment]
The idea (to be implemented) is: qore will go with all doxyfile templates for modules with approprate variables/paths in QoreConfig modules will use these files to build the docs. Profit: no file will be duplicated = less maintenance

**Comment by davidnich** [comment]
this is now working
