### ISSUE TITLE
configure.ac used datarootdir variable which is not set

### ISSUE THREAD

**Issue by pavelkveton** [qorelanguage/qore#1148]
we need to fix it in all autoconf modules and qore from 0.8.12 up

**Comment by davidnich** [comment]
bug is triggered when using autoconf 2.59 (such as on rhel5)

**Comment by pavelkveton** [comment]
reopening, the fix must be done also for qorus 3.0.4, aka for branch 3.2-2014-07-28 of module-oracle

**Comment by davidnich** [comment]
applied to Qore and all modules
