### ISSUE TITLE
format_number() and <float>::format() give incorrect results when rounding

### ISSUE THREAD

**Issue by davidnich** [qorelanguage/qore#1149]
ex:

```
qore -X '0.9.format(",.0")'
"0"
```

**Comment by tmandys** [comment]
Dne 4.8.2016 v 15:37 David Nichols napsal(a):

> |qore -X '0.5.format(",.")'|
> Also obsolete minus sign:

qore -X '(-0.4n).format(",.0")'
"-0"

## 

Tomas Mandys
Qore Technologies
Email: tomas.mandys@qoretechnologies.com
Tel: +420-604690589
Skype: tmandys@hotmail.com
