### ISSUE TITLE
FixedLengthUtil and CsvUtil: recent changes broke backward compatibility

### ISSUE THREAD

**Issue by gamato** [qorelanguage/qore#1163]
Recent changes to FixedLengthUtil module broke compatibility with old user code.
Examples:
- FixedLengthFileIterator used to be based on Qore::FileLineIterator class. Changing that means any methods & attributes provided by the base class are not available anymore. That can break a user code (and it did).
- FixedLengthFileWriter used to have a private attribute "file" holding name of the file being written. Private attributes can be used by child classes and thus this change can break a user code (and it did).

I'm not sure what to do here, but there are a few options:
- Do nothing. Not that many stuff depends on the changes and maybe it's okay (and easier) to change dependent code.
- Create new classes when doing such incompatible changes.
- Create new module(s) when doing such incompatible changes.

The last two options would allow both APIs, old and new, to be used as needed. They also allow for a new clean design based on current needs and experience gained, without having to carry over old compatibility cruft.

**Comment by omusil24** [comment]
We discussed this with @tethal, @davidnich and @pavelkveton AFAIK and decided that it was ok to change this.

**Comment by davidnich** [comment]
@omusil24 we were wrong - it caused compatibility issues with existing code - this is something we have to be sensitive to

there there are additional imperfect compromise options for this case in particular:
- `FixedLengthFileIterator`:
  - add methods from `ReadOnlyFile` to this class to try to maintain backwards-compatibility
  - add methods to `FileInputStream` from `ReadOnlyFile` and then place `FileInputStream` as a base class of `FixedLengthFileIterator`
- `FixedLengthFileWriter`: here we need to add back the `file` member in any case for backwards-compatibility

**Comment by davidnich** [comment]
CsvFileIterator in CsvUtil has the same issues
