### ISSUE TITLE
module-xml: WDSL normalize parsed xml

### ISSUE THREAD

**Issue by tmandys** [qorelanguage/qore#1183]
Data structure is defined in WDSL but structure of parsed xml in hash depends on actual data content. When using hash all cases must be handled via IFs.

E.g. when an optional attribute appers inside element then "^value^" is added, we must code both cases in code. Comment is similar case but it is not predictable from WDSL, parsing controllled by parse_xml() parameter.

Example:

```
<elem>
  value
 </elem>
hash parsed_xml = (
 'elem': value
);
# if optional attribute is possible (mandatory is always there so developer can hardcode proper code)`
<elem optional="opt">
  value
 </elem>

hash parsed_xml = (
 'elem': (
   '^attributes^': (
     'optional': 'opt'
   ),
   '^value^': 'value'
);
#or even unpredictable comment
<elem>
<!-- comment -->
  value
 </elem>
# parse_xml with comments
hash parsed_xml = (
 'elem': (
   '^comment^': 'comment',
   '^value^': 'value'
);
# so the developer who wants value need always do
if (parsed_xml.elem.typeCode() == NT_HASH) {
 value_is = parsed_xml.elem."^value^";
} else {
 value_is = parsed_xml.elem;
}

# I would add a function

any/string xmlGetElemValue(hash e) {
  if (e.typeCode() == NT_HASH) {
     return e."^value^";
  } else {
     return e;
  }
}
```

I'm not sure if the same problem is when adding hash of list when multiple elements are inside another element. Even it's defined in WDSL as min/maxOccurs then list is not added when there is only one element inside. 

```
<elems>
  <elem>
    val
  </elem>
</elems>
hash parsed_xml = (
  'elems': ('elem': 'val')
);

vs.

<elems>
  <elem>
    val1
  </elem>
  <elem>
    val2
  </elem>
</elems>
hash parsed_xml = (
  'elems': ('elem': list('val1', 'val2') )
);

#using in foreach statement it does for string and list the same way 
foreach (string e in (parsed_xml.elems.elem) {
   ...
}
# using with index it works using workaround
x = (()+parsed_xml.elems.elem)[0];

# if it is an issue then a new function may be more transparent:
list xmlGetElemAsArray(any e) {
  if (e.typeCode() == NT_LIST) {
    return e;
  } else {
    return list(e);
  }
}

```
When used in mapper as string definition then mapper = ("field": "elem.elem[.^value^]") should intelligently handle return value regardless "^value^" key.

**Comment by davidnich** [comment]
@tmandys I don't understand this issue - neither the summary nor the description - also there are no labels (is it a bug, is it a feature, is it c++ code or not - etc - I added the "module" label which is the only one that's clear for me) - can you please improve the summary and then if necessary can we discuss the description and the plan to fix whatever it is that you want to address with this?

Also I added milestone 0.8.13 and assigned to you

**Comment by davidnich** [comment]
@tmandys long-term, maybe we should consider instead returning objects instead of a hash for SOAP responses

the function you proposed sounds good, but please keep in mind that our naming convention states that functions should have `names_like_this()`; camel case names are reserved for class methods etc

**Comment by omusil24** [comment]
@tmandys What is the resolution to this? fixed, notabug, wontfix or duplicate? Please add the resolution label.
