### ISSUE TITLE
declaring a copy method as synchronized results in a crash when the method is called

### ISSUE THREAD

**Issue by davidnich** [qorelanguage/qore#1188]

**Comment by omusil24** [comment]
What about constructors, destructors, memberGate, methodGate and memberNotification? And also possibly declaring these functions static and/or final?

**Comment by davidnich** [comment]
@omusil24 AFAIK none of those methods are affected by this bug

if you try to declare a constructor or destructor final, you will get the error message it's not supported, and you should declare the class final, which is more correct from my point of view.  The other special methods are not inherited and therefore can't be declared `final` or `abstract`.

Furthermore, I don't see any value in allowing those methods to be declared `static`; it would complicate the implementation and be confusing in the code.

**Comment by omusil24** [comment]
Regarding `static`, I just wanted to make sure that it's already handled.

And regarding the `final` constructor - if it's like you say, then the Classes documentation should be fixed since it looks like it's allowed to have `final` constructor:

```
[[final] [private|public] [deprecated] constructor([[param_type] param_name [= default_initialization_expression], ...]) [: parent_class_name(args...), ...] {}]
```

**Comment by davidnich** [comment]
@omusil24 ok #1190 has been opened for this
