### ISSUE TITLE
Datasource automatically opens a connection during construction if there are options in the connection string

### ISSUE THREAD

**Issue by omusil24** [qorelanguage/qore#1201]
Connection string with options (ex. `pgsql:abc/def@omq{bla=test}`) leads to Datasource automatically opening a connection in constructor which should not happen AFAIK (according to docs). Automatic connection (calling `open()`) should only happen when 

> ...no connection has yet been established and a method is called requiring a connection to the database server.

The connection is opened through this series of methods:

```
1. static void ds_constructor_hash(...)
2. static int ds_set_options(...)
3. int ManagedDatasource::setOption(const char* opt, const QoreValue val, ExceptionSink* xsink)
4. DatasourceActionHelper(...)
5. int ManagedDatasource::startDBAction(...)
6. int Datasource::open(...)
```

This leads to the driver connection being opened without the options in the connection string set in the Datasource's option hash and therefore unavailable to the driver at that time.

If there are no options in the connection string, `ds_set_options()` does not call `ManagedDatasource::setOption()` and this problem does not happen.

**Comment by davidnich** [comment]
@omusil24 are you going to fix this or do you need someone else (me or Ondra) to work on it?

**Comment by omusil24** [comment]
@davidnich I would prefer you to fix it.

**Comment by davidnich** [comment]
ok, no worries - is it blocking you now BTW?
