### ISSUE TITLE
Implicit default constructor ignores private:internal access modifier on base constructor

### ISSUE THREAD

**Issue by tethal** [qorelanguage/qore#1242]
```
class A {
    private:internal constructor() {
        printf("Cannot be called\n");
    }
}

class B inherits A {
}

B b();
```

A's constructor gets executed even though it is internal. The correct behavior would be to report an error (preferably at parse-time) that B cannot inherit from A.

**Comment by davidnich** [comment]
caught only at runtime, #1275 covers the parse-time verification of these calls
