### ISSUE TITLE
trunc_str() never returns when a unicode char happens to be at the truncated length position

### ISSUE THREAD

**Issue by martin-zemek** [qorelanguage/qore#1327]
`trunc_str("asdfäzxcv", 3)` ... ok ... returns "asd"
`trunc_str("asdfäzxcv", 4)` ... **never returns**
`trunc_str("asdfäzxcv", 5)` ... **never returns**
`trunc_str("asdfäzxcv", 6)` ... ok ... returns "asdfä"  (5 chars)
`trunc_str("asdfäzxcv", 7)` ... ok ... returns "asdfäz"  (6 chars)

**Comment by davidnich** [comment]
retargeting to 0.8.11.x
