### ISSUE TITLE
StreamReader is buffered so any objects reading the same stream will get out of sync

### ISSUE THREAD

**Issue by davidnich** [qorelanguage/qore#1349]

**Comment by omusil24** [comment]
This was a wanted behaviour since it didn't make much sense anyway to have more sources read a byte stream at the same time.

**Comment by davidnich** [comment]
it makes sense when you have an input stream where you want to iterate it with lines (for example with `InputStreamLineIterator`) and then when you get to a certain point, read bytes, and then continue reading lines again - I just ran into this today while working on the documentation infrastructure and trying to port it to streams (for example this is done in `doxygen/qdx` now using `ReadOnlyFile` - I could not port to use streams because there is no possibility to use `StreamReader` in an unbuffered way).

I was looking at Java and it seems that the current `StreamReader` class should be `BufferedStreamReader` and the `StreamReader` class should be rewritten to be unbuffered to better mirror Java.

**Comment by omusil24** [comment]
I know. We did it also because of performance reasons.

**Comment by davidnich** [comment]
the fix seems easy - rename `StreamReader` to `BufferedStreamReader` and implement a non-buffered `StreamReader`.  The performance issues of buffering are clear, but buffering also breaks reading from a stream in the scenario that I mentioned above, so Qore needs to support a way to not have buffering when it's not needed as well.

Also it looks like in case there is a `\r\n` combination that spans two buffered reads (i.e. `\r` at the end of one and `\n` at the beginning of the next) the current code won't work properly

**Comment by davidnich** [comment]
@omusil24 another way to work around this issue would be to:
1) add a constructor to `InputStreamLineIterator` that takes a `StreamReader` argument instead of the `InputStream` argument
2) add a method to `InputStreamLineIterator` that returns the internal `StreamReader` object

either of those would allow us to work around the limitations of the current implementation and leave `StreamReader` as a buffered class - in which case anyway this fact needs to be documented properly.

I personally would prefer to do all 3) - implement the two items above plus implement a `BufferedStreamReader` class - then we could have `InputStreamLineIterator` create an internal `BufferedStreamReader` by default when created with the constructor taking the `InputStream` argument for performance reasons and still leave enough flexibility for other scenarios when necessary.

**Comment by omusil24** [comment]
Ok, sounds fine. Do you want to implement this or should I do it?

**Comment by davidnich** [comment]
@omusil24 please do it, thanks - also I would like to see a test where `\r\n` that spans a buffer with a buffered input stream passes a line parsing test

**Comment by omusil24** [comment]
@davidnich there are tests like these in the test/qore/classes/LineIterators/InputStreamLineIterator.qtest and test/qore/streams/string-reader.qtest files. The "buffer edge" tests.
Have you checked those? Is there something missing or wrong?

**Comment by davidnich** [comment]
no - great - I just suspected that it might not work from looking at the code - if it does, I'm happy to be wrong - no need for further action, thanks for bringing that to my attention
