### ISSUE TITLE
SqlUtil: SQL LENGTH is missing

### ISSUE THREAD

**Issue by alachata-qore** [qorelanguage/qore#1395]
SqlUtil misses SQL LENGTH function.

**Comment by gamato** [comment]
I just figured out this little trick that can be used with current SqlUtil:

Instead of:

```
where length (col_name) <= 10
```

one could use:

```
where substr (col, 10+1) is null
```

:-)

And there is `op_substr()` in current version of SqlUtil.

**Comment by pvanek** [comment]
actually SqlUtil misses much more than length()... there are tens of standard functions and hundreds specialized functions in different DBMS. I originally suggested something like op_function(string name, ...args...) which would be expanded to <name>(...args...) call, but it was rejected.

**Comment by alachata-qore** [comment]
I would suggest op_function(string name, ...args...)  again..

**Comment by davidnich** [comment]
@pvanek the reason it was rejected is because it would directly allow SQL injections
