### ISSUE TITLE
module-json: function parseJSON does not handle BOM in UTF-8 input

### ISSUE THREAD

**Issue by gamato** [qorelanguage/qore#1398]
Function `parseJSON` chokes on input text that contains UTF's BOM (byte order mark).

Note that Unicode standard does not recommend BOM for UTF-8 files:

> Use of a BOM is neither required nor recommended for UTF-8, but may be encountered in contexts where UTF-8 data is converted from other encoding forms that use a BOM or where the BOM is used as a UTF-8 signature.

But Qore should be able to process such input regardless.

**Comment by gamato** [comment]
Also, it just occurred to me that reading from UTF-8 encoded text files perhaps could / should omit BOM mark..?
Or maybe there should be a different way to cleanse a string (that is to strip it off of unwanted / unexpected stuff).

**Comment by omusil24** [comment]
@davidnich Where should this be fixed? 0.8.12 or develop?
