### ISSUE TITLE
add a variant with a base argument to <int>::toString()

### ISSUE THREAD

**Issue by davidnich** [qorelanguage/qore#1453]
so that integers can be converted to strings in a base other than base 10 - ex:
`10.toString(16)` == `"A"`

@martin-zemek I hope you don't mind me assigning this to you...

**Comment by martin-zemek** [comment]
The new function cannot be named `toString()` because there already exists the function `<number>::toString(int fmt)` and we certainly want the new function to have the same behaviour for both `<int>` and `<number>`. I propose the name `toBase()`.

**Comment by omusil24** [comment]
```toBase()``` function has been implemented for both int and number types in #1475

**Comment by martin-zemek** [comment]
Actually, the `<number> `version is not implemented correctly yet. It works only for numbers that are not longer than integers because it is implemented by calling the <int> version.

**Comment by martin-zemek** [comment]
`<float>::toBase(base)` implemented
`<number>::toBase(base)` reimplemented/fixed
