### ISSUE TITLE
do not include the port in the Host header when connecting to port 443 with SSL

### ISSUE THREAD

**Issue by davidnich** [qorelanguage/qore#1489]
the HTTP specification allows this (https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.23), but it causes some servers to refuse to serve the request.

wget does not include the port in this case

example of a server that refuses to serve the request: https://group.three.com/qcbin/rest/is-authenticated

this request fails with an infinite request loop:
```
wget https://group.three.com/qcbin/rest/is-authenticated --header="Host: group.three.com:443"
```

this request succeeds:
```
wget https://group.three.com/qcbin/rest/is-authenticated --header="Host: group.three.com"
```

for more info, see
```
qget -vvv https://group.three.com/qcbin/rest/is-authenticated
```

So even though our request with the port number in the HTTPS request (i.e. `Host: group.three.com:443`) is technically correct according to the spec, since wget (a tool with a lot of reviewers, specialized in HTTP requests) does not do this, and we have a real server that fails to serve the request when we do include it, and the spec also indicates that

> A "host" without any trailing port information implies the default port for the service requested

so if we omit the port in the case of an HTTPS request on port 443, we are still sending a valid request, I believe we should follow wget's lead here.

**Comment by omusil24** [comment]
I agree with this. Omit the port in case of SSL/HTTPS (443) and HTTP (80).

**Comment by pavelkveton** [comment]
I agree, let's go the wget's way...

**Comment by davidnich** [comment]
thanks for the feedback, @omusil24 can you please implement?

**Comment by omusil24** [comment]
@davidnich Sure. Which parts of code does this involve? Sockets or HTTPClient and HttpServer?

**Comment by davidnich** [comment]
@omusil24 only the HTTPClient object - see QoreHttpClientObject.cpp - check `qore_httpclient_priv::getHostHeaderValue()` and `qore_httpclient_priv::send_internal()` (for the proxy `Host` header)
