### ISSUE TITLE
Object support in Qorize

### ISSUE THREAD

**Issue by tmandys** [qorelanguage/qore#1575]
Qorize object instance even it's not perfect as private object members are not iterated and overloaded constructor has parameters.

**Comment by davidnich** [comment]
the only way to do this properly is to have some sort of `Serializable` abstract class like Java I believe - keep in mind that Qore 0.8.13 has true private members as well (`private:internal`) - is your branch for this on Qore 0.8.13?  There is no milestone value on this issue, so I can't tell.

**Comment by tmandys** [comment]
Sure, it's not perfect but better than nothing. I try to prepare "simple" case demonstrating wsdl problem I want to run Q program with data beyond real wsdl parser to have chance delete stuff non related to issue. In the worst case it's possible temporarily change private to public in source code (maybe general "debug-force-all-public" option would be helpfull). Is a non-documented way how to get from Q code private member values or at least member names - in this case code injection of a memberGate function returning value but how to get name list even inside class ... E.g.printf(%N) does dumping of all stuff.
