### ISSUE TITLE
Qore compilation failed (single-compilation-unit off)

### ISSUE THREAD

**Issue by tmandys** [qorelanguage/qore#1598]

**Comment by davidnich** [comment]
@tmandys can you please put the error you found in the issue report?  Also the milestone is important so it's clear in which branch the error occurred - if it's for `develop`, then it should be tagged `invisible` because the bug affects unreleased code only

**Comment by tmandys** [comment]
But in this case it just build issue related to a recent commit, missing header files in particular .cpp which may repeat many times so makes no sense put it in release notes
