### ISSUE TITLE
Improve InboundTableMapper performance with bulk inserts

### ISSUE THREAD

**Issue by davidnich** [qorelanguage/qore#1626]
InboundTableMapper bulk inserts should be made without converting the data to a list of hashes and then back again to a hash of lists - a hash of lists should be mapped in place and any constant or identify mappings should be made on the source list directly, which should bring performance up closed to that of `BulkInsertOperation`

**Comment by pavelkveton** [comment]
how this affects the user code? Will we have to change the existing user code when the grouping will change?

**Comment by davidnich** [comment]
the change will be 100% transparent - it's just about changing the internal implementation to use more efficient data structures - which should allow the same SQL approach as with BulkInsertOperation with mappers in common use cases (such as used now in user code in the Rossini project for example)

**Comment by pavelkveton** [comment]
ok then - nevertheless, as will have big impact on Rossini, I'd like to be also in reviewers to see what happened... thanks

**Comment by pavelkveton** [comment]
if we want it for Rossini, the milestone should change, right?
