### ISSUE TITLE
preprocessor: try-module meaning confusing

### ISSUE THREAD

**Issue by pavelkveton** [qorelanguage/qore#1648]
the documentation stands the following example of %try-module directive usage:
```
%try-module($ex) some_module > 2.0
    printf("error loading module %y: %s: %s\n", ex.arg, ex.err, ex.desc);
    exit(1);
%endtry
```

this example does not work - it requires a SPACE betwen try-module and left parenthesis, AND also it requires the dollar sign before 'ex' in the arguments to printf.

Nevertheless, even when this is fixed, let's suppose that you have a real (longer) example where there is a function or variable from some_module used after %try-module:
```
%try-module($ex) some_module > 2.0
    printf("error loading module %y: %s: %s\n", ex.arg, ex.err, ex.desc);
    exit(1);
%endtry

some_function_from_some_module();
```
In this case, the execution finishes with
```
unhandled QORE System exception thrown in TID 1 at 2017-02-06 06:23:30.380972 Mon +01:00 (CET) at zk.q:6
PARSE-EXCEPTION: function 'some_function_from_some_module()' cannot be found
```
i.e. with a parse exception that some_function_from_some_module() is not known. So the content of try-module block is never executed whenever the parsing fails (which will be the case in any real example).

The only point of using try-module is then to put another preprocessor directive here - all other code is "ignored" and the example in the documentation is highly confusing...

**Comment by davidnich** [comment]
the documentation is not clear - working on it now
@pavelkveton I will assign the pull request to you for review before Fanda merges it

however the other code is not ignored if there are no more parse errors in your code - if you refer to definitions provided by a module that's not loaded without wrapping them in defines that would be set in the `%try-module` block, then the error is in your code (based on a misunderstanding of how `%try-module` works) - I hope I'll be able to clarify it in the updated documentation.
