### ISSUE TITLE
dereferencing an invalid element should / could raise an exception

### ISSUE THREAD

**Issue by gamato** [qorelanguage/qore#165]
This seems error prone — “Dereferencing an invalid element (past the end of the list or with a negative number) will return NOTHING“ — we wouldn’t notice out of band access.

Suggestion: Raise an exception.

Yes, it's a design decision and I can see some advantages to it. But please consider a new parser directive to enforce new modus operandi as suggested.

**Comment by davidnich** [comment]
cannot easily change and adding a new option to provide this behavior would complicate the implementation which we're trying to avoid while planning for the qore-llvm release
