### ISSUE TITLE
SqlUtil's op_in() operator does not handle large number of elements when used with Oracle

### ISSUE THREAD

**Issue by gamato** [qorelanguage/qore#1660]
Passing too many elements to op_in() when using Oracle DB may fail.

Two possible scenarios have been identified:

1. specialised op_in() from OracleSqlUtil would fail with ORA-22165 / OCI-22165 as soon as more than 32767 elements are passed

2. generic op_in() from SqlUtil would fail with ORA-01795 as soon as more than 1000 elements are passed

**Comment by pvanek** [comment]
Please never ever use generic op_in for oracle. It will cause mess in shared memory of oracle server

**Comment by davidnich** [comment]
@gamato @pvanek I see two issues here, of which only one is clear to me how to solve:
1) SqlUtil should make `op_in()` work with arbitrarily large argument ranges if technically possible - no problem to document that it's bad practice to use too large lists here (but we should define how large the lists should be to make them reasonable and also why)
2) how to describe to users how to make queries selecting a large number of keys/ids known at runtime and not in the database - this is not clear to me how to do it if `op_in()` is not appropriate

**Comment by pvanek** [comment]
ad 2 - I'd say we should suggest to use joins as much as possible. op_in() is fine, but the design of "select IDs and use t in further processing" is not efficient

**Comment by davidnich** [comment]
@pvanek the case with joins is clear, but what guidance should we give about the cases when we are dealing with data that's not in the DB?

**Comment by gamato** [comment]
1. It should be possible on Oracle with a user (us) defined table type. The builtins we use are defined with limit of 32767 elements. I'm not sure what options there are on other databases. Therefore it's very likely we are not able to do it transparently without any limits. .... Actually, there's another option -- inserting values into a (temporary) table and using that one in a join. But I don't like it for multiple reasons.  I mean trying to do it transparently without users actually knowing what's going on in the background.  Users should be aware of what they do to at least a certain extent.

2. Databases are designed to hold and process large amount of data. It's natural to store data, even temporarily, and lets DB engines to do the work. We can put a notice / suggestion to op_in() documentation and we should think how we use it ourselves (Qorus).
