### ISSUE TITLE
In Select Option Hash "columns" : ("*")   with join clause selects only data from left table

### ISSUE THREAD

**Issue by alachata-qore** [qorelanguage/qore#167]
hash sh = (
        "columns" : ("*"),
        "where" : ("h1uk_proc_status" : "CLOSED"),
        "join" : join_inner("right_table", "right", ( "id" : "id")),
 );

selects only data from left table.

See http://qore.org/manual/current/modules/SqlUtil/html/sql_operations.html#select_option_hash

**Comment by davidnich** [comment]
this is the correct behavior - if you leave out the "columns" key, you will get all columns from all tables

if you want the columns from a particular table, then you can use the asterisk - without a prefix, it means the main table, with a table alias, it means a table from the join clause
