### ISSUE TITLE
sqlutil: schema alignment skips column with name "driver"

### ISSUE THREAD

**Issue by pvanek** [qorelanguage/qore#1684]

**Comment by davidnich** [comment]
this change breaks existing schemas using the `driver` key in the column description hash - we need to decide how to handle this - either have some backwards-compatibility logic in the fix (i.e. look if the `driver` key is really a column or a driver override hash and use appropriately) or some way / docs about replacing this functionality

```
ST02 /Users/david/src/Qorus/test/qlib/SqlUtil.qm:8746: COLUMN-ERROR: pgsql:omq@omq: table public.workflow_instance column "driver": no native_type or qore_type keys in column option hash: {oracle: {custom_status: {qore_type: "string", size: 1, comment: null}}, mysql: {modified_date: {native_type: "date"}}}
```

**Comment by davidnich** [comment]
@pvanek please always ensure that there's a milestone when working on issues
@omusil24 please do not close an issue without a milestone (i.e. add the milestone first if it's missing)
