### ISSUE TITLE
improve QUnit assertion failure output to include more stack information to cover the case when multiple test modules are used

### ISSUE THREAD

**Issue by davidnich** [qorelanguage/qore#1720]
QUnit currently reports the last non-module location in an assertion, however the actual error could have been in a module (or QUnit itself); more stack information would be useful

Possibly the best solution would be to display a full stack trace with verbose >= 1

**Comment by davidnich** [comment]
or maybe just to show the whole stack trace for all assertion failures - assertion failures should not happen anyway (what I mean by this is that tests are supposed to pass, if they fail, then as much info as possible should be shown)

**Comment by davidnich** [comment]
@omusil24 I assigned this to Jan because I assume you're not working on it, and he's interested in fixing it - if it's a problem let me know - my fault, not Jan's :)

**Comment by omusil24** [comment]
No, it's ok. I have looked at it only briefly before I left so no problem.

**Comment by davidnich** [comment]
needs an additional modification to address situations like:
```
+ OK: "REGRESSION-TEST" assertion in <start> :-1 -> QorusRegression::constructor() at ./QorusRegression.qtest:376 -> QorusRegression::rpcTest() at ./QorusRegression.qtest:1560
```

the `<start> :-1` should not be there as it doesn't provide any value
