### ISSUE TITLE
add support for "structs" or typed hashes

### ISSUE THREAD

**Issue by davidnich** [qorelanguage/qore#1724]
similar to objects:
* structs will be declared like classes
* keys (like members) must be declared
* keys can be initialized when created

different from objects:
* no methods
* passed by value (do not participate in GC)

similar to hashes:
* passed by value

unique creation method:
* constructor-like creation, a hash can be passed giving initial values for the struct

ex:
```
struct Example {
    int x = 1;
    string val = "default value";
}

# creates with the default values
Example ex1();
# overrides default values
Example ex2((x: 2, val: "xxx"));
```

Allows for type-safe data structures without GC cost - will vastly improve performance with the WSDL module and very large WSDLs without requiring GC optimizations (which need to be done anyway but will take more time).

Related to #990

**Comment by pvanek** [comment]
hmm, so the only difference between 

```
struct Example {
    int x = 1;
    string val = "default value";
}
```

and

```
class Example {
  public {
    int x = 1;
    string val = "default value";
  };
}
```

is only the GC (and public block)? In that case we don't need any new object type, just to fix GC (if possible) right?

**Comment by davidnich** [comment]
@pvanek yes also that there are no methods with `struct`s - so creation (aka struct construction) is simpler in this proposal - if you mean the internal implementation then it will be much simpler and I would probably create a new c++ class - for example some of the most complex code in objects is related to locking and lvalues, etc - in this respect from the point of view of the internal implementation, `struct`s would be exactly like hashes (except with type-safety of keys).

**Comment by pavelkveton** [comment]
from the language point of view, I can agree with @pvanek that it does not make much sense - it only adds a new way how to do something that is already possible (see Petr's example).

Suppose I can use class or struct or hash - what is the criteria which one should I use? Do I have to consider GC troubles while writing the code?

I would say: either let's fix GC (as Petr suggests). Or what about a class with only public members and no methods, and use special (struct like) implementation for it?

If we want to have simply-to-use and developer-friendly language, we cannot put more responsibility on a developer where the language itself can choose best implementation...

**Comment by davidnich** [comment]
@pavelkveton maybe you had an offline conversation with Petr and have more info, but I did not take Petr's questions as implying that my proposal didn't make sense (and he certainly did not outright say that).  Also I pointed out in my reply to Petr that his assumptions were not totally correct.

In short, this proposal does not add a new way to do something that is already possible.

The idea is to created a "typed hash" which would be passed by value - this is the main difference  between what you and Petr are describing and what I'm actually proposing - objects are passed by reference (technically it's like Java - by a copy of a reference to the object) and not by value.

Support for a "typed hash" allows us to have hashes with explicitly-declared keys (with their own types) but always passed by value, which makes them a very different data structure than objects.

Making improvements to the garbage collector is definitely desirable, but independently of that having a "typed hash" could be a valuable addition to the language anyway.

It's not meant purely as a workaround for performance issues in the GC, but because it could be valuable anyway - it fixes a design gap in the language (see #990 for a reference - this proposed feature would solve that issue in another way) - it could coincidentally *also* be used to work around GC issues.

Note that the syntax I documented above is only a proposal - we could support the declarations in another way - but just to ensure that the point sinks in - the idea is to add support for "typed hashes" rather than to implement a special case of an object.

**Comment by pvanek** [comment]
how it could handle "dynamic aspects of standard hash"? For example:

What will happen in case of eg. assigning a value to non existing member/key?

```
Example ex1();
ex.foo = 1;
```

What about this?
```
Example ex1();
delete ex1.x;
ex1.x = 'foo'; # type error? or new key definition?
```

or do I understand it wrongly and it will be real statically defined struct with known members in time of parsing/compilation? With no way for using hash-like features?

How hard would be to also implement a "typed list"? Which makes sense in this perspective too

**Comment by davidnich** [comment]
@pvanek 
> how it could handle "dynamic aspects of standard hash"? For example:
> What will happen in case of eg. assigning a value to non existing member/key?

If the key was not declared in the `struct`, then it will be a parse-time error (in case the parser knows that the lvalue is a `struct` of a given type) or a run-time error (in case insufficient info is available at parse time).

The second example is the same - it would be handled like an object of a particular class regarding parse- and runtime checking of valid keys.

> or do I understand it wrongly and it will be real statically defined struct with known members in time of parsing/compilation? With no way for using hash-like features?

It will be a structure with known members to be enforced at parse- and runtime, that is correct.  I don't know what you mean by "hash-like features" - the intention is that it is a typed hash - meaning that it's just like a hash except that keys must be defined and the data types of the keys will be enforced - otherwise it should have all the properties of a hash - meaning key order and very fast random key access - also fast iteration, etc.  The only difference will be that key types are known and enforced.

**Comment by tmandys** [comment]
What about implementing a class "final" attribute which will define classes in time of "compilation", i.e. no runtime method/field modification/injection allowed. Developer can define with or without methods, so "compiler" may create corresponding representation (with or without virtual method table), prepare quick member resolving etc. Params by value vs. reference is probably not issue worth implementing struct now.

**Comment by pavelkveton** [comment]
to sum up for myself:

- a `class` instance is always passed by reference, can have only fixed (and typed) members and also can have methods
- a `hash` is always passed by value, can have arbitrary members and cannot have methods

we propose for a `container` (working proposal `struct`) that
- has got fixed (and types) members (**for code safety**)
- is passed by value (**to avoid GC cost** --- **_any other reason here?_**)
- cannot have methods **except the initializer**

We follow Java's and (AFAIK) Python's approach in Qore, i.e. passing `class` instances by reference and other things by value. Although, we have an option to pass a `reference` too - consider this (IMHO very bad) possibility to express the same thing in two ways:
```
3.1.0 kveton@kvela ~$ qore -ne "class mmm {public { int r; }}; nothing sub xxx(reference a) { a.r=10; } mmm e(); xxx(\e); printf(\"%y\\n\",e);"
{<mmm object>: r: 10}
3.1.0 kveton@kvela ~$ qore -ne "class mmm {public { int r; }}; nothing sub xxx(mmm a) { a.r=10; }; mmm e(); xxx(e); printf(\"%y\\n\", e);"
{<mmm object>: r: 10}
```
Introducing another special container with implicit properties would only add to this confusion.

What about to introduce an option to pass an object (i.e. a `class` instance) by value - e.g. by specifying in the function header:
```
nothing sub xxx(mmm  by_value a) { a.r = 10; } # does not touch the object in caller's scope.
```

I.e. the `struct` effect would be achieved by using `class { public {...}};` and passing it with `by_value` keyword. The advantage is that if you spot `by_value` in the parameter declaration, you immediately know that "this is something special".

With `struct`, you put additional demand on a developer (or also a reader of the code) to understand the subtle differences between `class`, `struct` and `hash` and their behavior when passed somewhere..

**Comment by davidnich** [comment]
@tmandys there is already a `final` attribute for classes which means they can't be subclassed.

The whole point of this proposal is to implement "typed hashes" so that a hash can have type-safe keys.  The point about passing by value vs passing by reference is fundamental to the proposal as well due to the impact on GC.

**Comment by davidnich** [comment]
@pavelkveton in my opinion your proposal is more complicated than the one documented here.   Passing objects by value cannot be easily supported either - it would mean performing a copy operation on each "pass by value" call (i.e. a method evaluation) as well.

> is passed by value (to avoid GC cost --- any other reason here?)

A `struct` would be passed by value because it's a "typed hash".  The whole idea is to add type-safety to hashes.

> cannot have methods except the initializer

I am not proposing any methods at all - I'm just proposing a way to initialize the "typed hash".  There would be no way to implement any methods of any kind with a `struct`.

For me a "typed hash" is a natural and clean extension to Qore whereas changing object semantics or trying to implement this proposal using special cases of objects would make the language more complicated & less clean.

I have the feeling that discussing passing by value / reference and the GC issues are providing unnecessary confusion, though these are purely coincidental to this proposal designed to introduce "typed hashes" to Qore.

**Comment by davidnich** [comment]
@pvanek wrote
> How hard would be to also implement a "typed list"? Which makes sense in this perspective too

This is related to the complex type proposal that Ondra made - so it's a different subject actually.

Basically we're still taking about an extension to the hash to allow each member to be declared with its type.

For something like a typed list - it would be like `list<int>` (per Ondra's proposal), meaning a list that contained only integers - so the equivalent for hashes would be `hash<string,int>`, meaning that the hash keys would be strings and the values would all be ints.  So it's a different proposal than this one (but still one to be implemented in the future)...

**Comment by davidnich** [comment]
so also to add - my idea would be that this data structure would really be an extension to a hash - so a "typed hash" - meaning that it would be compatible with `hash` - so something like the following would be possible:

```
struct MyStruct {
    int x = 1;
    string str = "string";
}

# assigning a hash to a "struct" would work as long as the key 
# types are assignable (i.e. subject to parse- and runtime type checking)
MyStruct my_struct = (
    "x": 2,
    "str": "other",
);

# assigning a struct to a hash would always be possible without restrictions
hash h = my_struct;
```

Instead of `struct` we could use `hashdecl` or maybe something else (like `container` for example although I personally prefer one of the other ones).

**Comment by pvanek** [comment]
another idea from today's morning. What about not to introduce new "struct" or "hashdecl", but just extend "hash" to keep the 100% compatibility with no more new types.

My idea is to provide "properties" for standard hash

Reasons why is that to use this approach are:

- statically defined "struct" structure is very limiting - it for example cannot allow you to use nice features for "struct" created on DB table - to define struct structure runtime.
- there are non-compatible conversion between struct and hash
- there can be various properties, not only "struct-like" behavior

so what about to use something like this?

```
hash h;
h.setTypes( ( "x" : NT_STRING, "foo" : NT_INT) );
h.x = "abc"; # OK
h.foo = "abc" # RUNTIME-TYPE-ERROR
```

or also with "constructor" of hash( hash h), where h can be real hash with eg. optional keys "^types^", "^init^"... the char ^ is usually used for "metadata" in XML and Oracle modules.

```
hash h = hash( ( "^types^" : ( "x" : NT_STRING, "foo" : NT_INT),
                 "^init^" : ( "x" : "abc", "foo" : 1),
             ) );
printf("%n\n", h.types()); # prints True, because "^types^" or ^types^ hash - it's just proposal, API to be defined
```

Of course there can be more attributes, eg. my long time requested strict key access:

```
hash h = ( "foo" : "bar" );
h.setStrictKeys(True);
printf("%n\n", h.foo) # OK, key exists
printf("%n\n", h.mykey); # NON-EXISTING-KEY-ERROR for example raised
```

**Comment by davidnich** [comment]
@pvanek I would prefer a solution that provides parse-time type safety - runtime-only checks are a step backwards in my opinion.

This proposal is designed to address your strict key access issue but with parse-time type safety as well as runtime safety.

**Comment by davidnich** [comment]
I was also thinking about how it should look from the syntax perspective.

I think it would be confusing if we implemented it like a class name, I believe that ideally we should find a way to make it obvious from the source if the type is a class name or a "typed hash" name (for example in a function or method signature).

So I was thinking about using a form of Ondra's type proposal - if a hash with explicit types would be declared `hash<keytype, valuetype>`, then a "typed hash" could be declared simply `hash<hashdecl_name>`.   

So something like

```
hashdecl MyHashType {
    int i = 0;
    string str = "string";
}

hash<MyHashType> sub my_func() {
    return new hash<MyHashType>();
}
```

like this you can see immediately what the type is.  Also it will be compatible and complementary to Ondra's complex type proposal for Qore.
