### ISSUE TITLE
HashListIterator fails to iterate hash keys with single values

### ISSUE THREAD

**Issue by davidnich** [qorelanguage/qore#1738]
The `HashListIterator` class was designed specifically to iterate data in "hash of lists" format, which has always been the most efficient format for retrieving SQL data in Qore.  With the introduction of "Bulk DML" support in Qore 0.8.12, this format also became the most efficient format for input data as well.

With bulk DML input data, hash keys can be assigned single values as well as lists; the single value indicates that it should be used for every output value corresponding to every list element in the other keys (which must all have the same list size).  Unfortunately the `HashListIterator` class was not updated to cover this case, however it is used in various places to iterate this data.

Currently if a single value is used in such a hash, the `HashListIterator` class will throw an exception like:
```
HASHLISTITERATOR-ERROR: hash key 'code1' is assigned to type 'string'; expecting 'list'
```

Instead the single value should be included in every output hash as the value of the given key (as originally intended and as used in bulk DML binds for example).

This affects the `HashListIterator` class and therefore the `<hash>::contextIterator()` pseudo-method as well.

Furthermore the current `HashListIterator` class does not throw an exception if lists are different sizes, but this indicates an error in the data, and therefore is a situation where invalid data is silently ignored.

**Comment by pavelkveton** [comment]
@davidnich it is not clear to me whether this affects the current user code or not - was this bug introduced recently with fixing something else, or is it there from "beginning" of 0.8.12?

**Comment by davidnich** [comment]
I'm not sure if it affects user code or not either - this is there since the beginning of 0.8.12.  However note that if it affects user code, this change will make things work and will not break existing code.  The affect that not fixing this bug might have on code is that code that someone assumes will work will not, not that something that's already working will stop working.
