### ISSUE TITLE
allow_dot and allow_output_dot Mapper options are not recognized

### ISSUE THREAD

**Issue by pavelkveton** [qorelanguage/qore#1756]
allow_dot and allow_output_dot options are not present in Mapper class OptionKeys, and as such using them in options produce the exception
```
            foreach string k in (opts.keyIterator()) {
                if (!ck{k})
                    error("unknown option key %y passed to %s::constructor(); recognized option keys: %y", getFieldName(k), self.className(), ck.keys());
            }
```

note that this has also an impact on the "struct" modifier - acc. to the documentation: `this option is only necessary in place of the "name" option if the allow_dot option is set, otherwise use "name" instead`,

so basicly it is not possible to use "struct" properly now.

I suggest we remove "struct", "allow_dot" and "allow_output_dot" completely.

**Comment by davidnich** [comment]
these options are necessary in theory to allow for input and output field names with dots (`.`) in them - if we do not have these options, we cannot support any input or output field names with dots in them, which in case of such a requirement would be a major weakness of the Mapper module.  I would prefer to make them work properly & add tests etc.
