### ISSUE TITLE
function accepting a hash does not accept a variable declared as a hash

### ISSUE THREAD

**Issue by pavelkveton** [qorelanguage/qore#1770]
```
class A {
    public {
        hash h;
    }

    nothing xxx(hash x) {
        printf("%y\n", x);
    }

    bbb() {
        xxx(h);
    }
};

A a();
a.bbb();
```
running with `qore -n`, I get the following:
```
unhandled QORE System exception thrown in TID 1 at 2017-03-20 21:46:08.096270 Mon +01:00 (CET) in A::bbb() (zk1.q:11, user code)
RUNTIME-TYPE-ERROR: parameter 1 ('x') expects type 'hash', but got no value instead
call stack:
  1: A::bbb() (zk1.q:16, user code)
```
Considering that both the member `h` and the parameter `x` are declared (for the first sight) in the same way, it is strange.

I understand that a `hash` is `NOTHING` by default, but this is confusing.

**Comment by davidnich** [comment]
should be covered under:
* https://github.com/qorelanguage/qore/issues/488
* https://github.com/qorelanguage/qore/issues/187
