### ISSUE TITLE
implement support for ranges for lists and iterators as well as list slices

### ISSUE THREAD

**Issue by davidnich** [qorelanguage/qore#1781]
perl supports ranges and list slices like:
```perl
@array = (1..10);
my($card_num, $count) = (split /:/)[1, 5];
```

Qore currently has no way of creating a sublist of a list without modifying the list except by using the [select](https://docs.qore.org/current/lang/html/operators.html#select) or [map](https://docs.qore.org/current/lang/html/operators.html#map) operators.

**Comment by martin-zemek** [comment]
So far, the following has now been implemented:

1.  new range operator **..**
    - **2..4** returns **(2,3,4)**, **5..2** returns **(5,4,3,2)** (returns the same list as **range(start, stop, 1)**)
    - high precedence:
     **(3+2)..(4*3)** - parentheses are necessary
     **list y = b ? 5..8 : (6,2,4);**  - is the same as **list y = b ? (5..8) : (6,2,4);**
     **(4, 7, 8..6, 4)** - is the same as **(4, 7, (8..6), 4)**

2.  extended square bracket operator
    - the square bracket operator now accepts also list expressions, for example
    **(7,3,5,1,8)[3,1,4]**  returns **(1,3,8)**
    **list ls = (1..3); (7,3,5,1,8)[ls]**  returns **(3,5,1)**
    **(4, (8,3,4), 'asdf', 5, {"f":3, "g":2}, 1) [1 .. 4]** returns **((8,3,4), 'asdf', 5, {"f":3, "g":2})**

    - works also for strings and binaries:
    **"nriowgia"[5,1]** returns **"gr"**
    **"nriowgia"[3..6]** returns **"owgi"** (substring)
    **\<3e82cab0bb2ca4\>[2..4]** returns **\<cab0bb\>**
    (and so **\<3e82cab0bb2ca4\>[2..4][1]** returns **176** (= **b0** in hex))

     - since the existing behaviour of out-of-range indexes (for the case of list) was, for example:
    **(7,3,5,1,8)[12]** returns **NOTHING**
    the list expressions in indexes have been implemented to be tolerant as well:
    **(7,3,5,1,8)[3..7]** returns **(1, 8, NOTHING, NOTHING, NOTHING)**
    **(7,3,5,1,8)[6..2]** returns **(NOTHING, NOTHING, 8, 1, 5)**

    - since the existing behaviour of non-integer indexes was converting them to int, for example:
    **(7,3,5,1,8)[2.5]** returns **(7,3,5,1,8)[2] = 5**
    **(7,3,5,1,8)["zxcv"]** returns **(7,3,5,1,8)[0] = 7**
    the list expressions in indexes have been implemented in the same manner:
    **(7,3,5,1,8) ["x", 4, "3dfsa"]** returns **(7,3,5,1,8)[0,4,3] = (7,8,1)**
    
       note that in the case of the following expressions:
       **(7,3,5,1,8)[(3,1,4)]**  returns **(1,3,8)**
       **list ls = (3,1,4); (7,3,5,1,8)[ls]**  returns **(1,3,8)**
       we have actually changed functionality (rather than extended functionality) because formerly they would return **(7,3,5,1,8)[0] = 7** (converting list to int gives **0**)


Questions:
1. Is the behaviour ok, or should something behave differently?
2. How do you imagine the "support for iterators"? Can you give an example?
   Could, for example, three dot (**...**) operator return **RangeIterator**
        (**3...5** would return iterator over the range **3..5**)?

**Comment by omusil24** [comment]
> since the existing behaviour of out-of-range indexes (for the case of list) was, for example:
> (7,3,5,1,8)[12] returns NOTHING
> the list expressions in indexes have been implemented to be tolerant as well:
> (7,3,5,1,8)[3..7] returns (1, 8, NOTHING, NOTHING, NOTHING)
> (7,3,5,1,8)[6..2] returns (NOTHING, NOTHING, 8, 1, 5)

IMO the `(7,3,5,1,8)[3..7]` should return `(1,8)`, ie. instead of producing `NOTHING` values, no values should be produced, which is the same as the original out-of-range index operation. That `NOTHING` was meant as no value, not `NOTHING` value.

**Comment by davidnich** [comment]
@martin-zemek wow that looks really good.  

I did not look at the code yet, but to answer your questions:
> Is the behaviour ok, or should something behave differently?

it looks good to me

> How do you imagine the "support for iterators"? Can you give an example?
> Could, for example, three dot (...) operator return RangeIterator
> (3...5 would return iterator over the range 3..5)?

Basically the operator's implementation should implement the `FunctionalOperator` interface (in `qore/intern/FunctionalOperator.h`).  This will allow these expressions to support lazy evaluation with functional operators and also the `foreach` statement, for example.

So when you have an expression like:
```
int a = 1;
int b = 100000000;
map do_something($1), a..b;
```
or
```
int a = 1;
int b = 100000000;
map do_something($1), large_list[a..b];
```

It will not create a huge list and then iterate over the list but rather will return each element when it's needed.

See `QoreKeysOperatorNode` for an example, and let me know if you have any questions or comments.

It looks very good so far!

**Comment by pvanek** [comment]
I'd like to see also this functionality (like Python has):
(1,2,3,4,5)[2..] resulting in (3,4,5) = give me rest of list starting at index 2
(1,2,3,4,5)[..2] resulting in (1,2,3) = give me begin of list up to index 2

Personally I don't care if the operator will be ".." (Ruby, Perl) or ":" (Python, R) ;)

I'm not sure about "out-of-range" behavior. I'd like to see a runtime exception rather than added NOTHINGs

**Comment by martin-zemek** [comment]
As to the out-of-range behaviour, I agree with @omusil24 - since really "NOTHING means no value, not NOTHING value". So:
`(7,3,5,1,8)[3..7]` will return `(1,8)` and
`(7,3,5,1,8)[13..17]` will return `()` (empty list).
(Note the difference: `(1,2)[(5,)]` will return `()` while `(1,2)[5] `will return `NOTHING`.)

If we wanted to throw an exception we would have to change existing behaviour of simple-value indexes to throw an exception as well - to be consistent.

**Comment by martin-zemek** [comment]
Now also the unbounded ranges are implemented:
`(1,2,3,4,5)[2..] = (3,4,5)`
`(1,2,3,4,5)[..2] = (1,2,3)`

Accordingly, behaviour of "decreasing ranges" (left index is greater than right index) has been changed to return an empty list/string/binary:
`(4..2) = ()`
`(1,2,3,4,5)[4..2] = ()`
`"asdfzxcv"[4..2] = ""`
`<abcdef123456>[4..2] = <>`

**Comment by martin-zemek** [comment]
Now also the unbounded ranges are implemented:
(1,2,3,4,5)[2..] = (3,4,5)
(1,2,3,4,5)[..2] = (1,2,3)
(1,2,3,4,5)[..] = (1,2,3,4,5)

Note that since expressions like 2.. (unbounded ranges) cannot exist on their own but only inside square brackets a new node had to be introduced: **QoreSquareBracketsRangeOperatorNode**.
So, there are 2 new nodes:
  **QoreRangeOperatorNode**
  **QoreSquareBracketsRangeOperatorNode**
(and existing node **QoreSquareBracketsOperatorNode** has been modified to accept also list expressions inside).

Note that **QoreSquareBracketsRangeOperatorNode** is created not only for expressions like
(1,2,3,4,5)[..2] but also for bounded-range expressions (1,2,3,4,5)[0..2],
while for (1,2,3,4,5)[(0..2)] **QoreSquareBracketsOperatorNode** with a **QoreRangeOperatorNode** subnode are created.

The 2 new nodes implement **FunctionalOperator** interface and so in expressions like
```
  foldl $1 + 2*$2, 1..5;                               (=29)
  foldl $1 + 2*$2, (1,2,3,4,5)[2..0];                  (=9)
  map $1 + "*", "asdfzxcv"[6..3];                      (=("c*", "x*", "z*", "f*"))
```
lazy evaluation is applied.
But lazy evaluation is NOT applied in
 ```
  foldl $1 + 2*$2, (1,2,3,4,5)[(2..0)];
  map $1 + "*", "asdfzxcv"[(6..3)];
```
because **QoreSquareBracketsOperatorNode** does not implement **FunctionalOperator** interface.
                
For more examples on the new functionality, see the method rangeAndSlice() in test/qore/operators/operators.qtest (branch feature/1781_list_slices_and_ranges).

**Comment by davidnich** [comment]
@omusil24 @martin-zemek 
> IMO the (7,3,5,1,8)[3..7] should return (1,8), ie. instead of producing NOTHING values, no values should be produced, which is the same as the original out-of-range index operation. That NOTHING was meant as no value, not NOTHING value.

This is a problem for assignments - take for example the following:
```
list l = (0,1,2,3,4);
(*int i0, *int i1, *int i2) = l[0,7,2];
```

If you have an arbitrary list `l` and you expect to assign the given indexes of that list, then the return value must be the value at that index.  Only `NOTHING` is appropriate in that case.  If we just silently ignore invalid indices and skip them, then we can quietly break things in a very confusing way in situations like the above.  

So `NOTHING` meaning "no value" is potentially an appropriate return value in such cases - we have to assume that the user is relying on the return value to return the value in that position in the index list.

The other alternative is to throw a runtime exception (and also implement appropriate parse-time checks) when referencing list,string, or binary indices outside the range of the indexed object, however this then introduces different behavior for the slice operation as with the single element dereference operator - classic `[]` when dereferencing outside the indexed object is to return `NOTHING`.

So to have a consistent solution and avoid introducing confusing semantics, I would suggest returning `NOTHING` when dereferencing lists outside the list range and ignoring invalid references for `string` and `binary` - which is actually consistent when you consider that adding `NOTHING` to a `string` or `binary` results in no change whereas adding `NOTHING` to a list appends this value to the list.

**Comment by omusil24** [comment]
Ok, this makes sense... So let's return NOTHING values for invalid indices...

I just didn't understand this part in the last paragraph:

> ignoring invalid references for string and binary

What do you mean by that?

**Comment by davidnich** [comment]
> ignoring invalid references for string and binary

I mean how it's implemented now in `feature/1781_ranges_fixes` - it means that the `[]` slice operator ignores invalid indices for strings and binaries but returns `NOTHING` for the requested elements when making a list slice.

**Comment by omusil24** [comment]
Ok, so the final state, after this change will be implemented, is that using slices and ranges which are invalid/out-of-range on a list will produce list with `NOTHING` values at the appropriate positions, and using them on a string/binary will produce a string/binary with data from the valid indices only (ignoring the invalid/out-of-range indices).

**Comment by davidnich** [comment]
@omusil24 
> Ok, so the final state, after this change will be implemented, is that using slices and ranges which are invalid/out-of-range on a list will produce list with NOTHING values at the appropriate positions, and using them on a string/binary will produce a string/binary with data from the valid indices only (ignoring the invalid/out-of-range indices).

yes, that's how it's currently implemented

**Comment by omusil24** [comment]
Ok... So, the only change that needs to be done is add back the NOTHING values for the list...

**Comment by davidnich** [comment]
@omusil24
> Ok... So, the only change that needs to be done is add back the NOTHING values for the list...

already done in my branch - now I'm working on lvalue support - i.e. slice support in lhs values in lvalue expressions
