### ISSUE TITLE
add tests and review Mapper and TableMapper

### ISSUE THREAD

**Issue by pavelkveton** [qorelanguage/qore#1782]
dump of my notes/issues to check:

           ! queueData mixed with insertRow - ensure that it raise exception immediately (at latest on stmt mismatch)
            - test the examples in comments/doc in TableMapper.qm
            - const mapper passed with "insert_block = 1" differs from "insert_block > 1"?
            - const mapper - when passed via queueData() it is inserted for
              each insert_block once, right?
                -> constant map is flushed only once in the end with flush()
            - add more thorough example for mappers with bulk?
            - add a test for "struct" in TableMapper
            ? some comment from David regarding table.insert()?
            ? FIXMEs in the code and in the tests
            - add a test for "subclass" modifier - seems unused
            ? cdata check with bulks? - see mapFieldIntern() (unused in Rossini)
            ? ostruct
                ? what if ostruct top-level name collides with some existing name in the output fields?
            ? avoid separate branches for "insert_block" = 1
            ? test for 'maxlen' in mapper spec - unused in Rossini
            - add a test for "type" modifier - unused in Rossini
            - test:
                ? const+sequence maps only?
                ? what if empty hash on input of queueData?

Putting into 0.8.12 since most of the issues don't affect existing code and it is more about writing the tests

**Comment by davidnich** [comment]
Mapper tests are sufficient as mapper types are deprecated and advanced I/O functionality is in DataProviders and sufficient Mapper tests have been added
