### ISSUE TITLE
module-ssh2: allow for on-demand connections in SftpPoller.qm

### ISSUE THREAD

**Issue by pavelkveton** [qorelanguage/qore#1846]
currently the `SftpPoller` opens connection on its constructor (`sftp.connect()`) and keeps it persistent through all its life.

This can cause problems when the connection is broken - `connect()` is never called again.

We can consider keeping this persistent connection, but reopening when not connected on each operation, or (my favourite) open the connection on-demand (i.e.on every operation).

The latter one could be time/cpu expensive, though, so maybe we want to support both or so.

**Comment by pavelkveton** [comment]
this would probably break some backward compat, targettng to 0.9

**Comment by galvani** [comment]
@pavelkveton How would it break compatibility?

**Comment by galvani** [comment]
This sounds like two proposals:
_We can consider keeping this persistent connection, but reopening when not connected on each operation, or (my favourite) open the connection on-demand (i.e.on every operation)._
I propose: 
 * **Every action will verify the connection was open and it is alive; if not connection will be recreated**

This is equals to **connecting on demand** and it is completely backwards compatible

**Comment by omusil24** [comment]
That's the first option Pavel proposed. Currently if the connection is broken, no reconnect happens. He proposed doing that reconnect when some operation is called and the connection is currently broken.

**Comment by omusil24** [comment]
The second option means:
- don't do any connection by default
- on operation request: connect, do operation, disconnect

**Comment by gamato** [comment]
The second option would change current behaviour and thus could break compatibility (as now it is expected that when SftpPoller is created the connection was already successfully made).

So I would keep the current behaviour and add automatic reconnection which seems useful.  Maybe a new option should control this behaviour.
