### ISSUE TITLE
runtimeFindVariant to accept paramTypeInfo parameters

### ISSUE THREAD

**Issue by tmandys** [qorelanguage/qore#1865]
Implement function to find `AbstractQoreFunctionVariant` by paramTypeInfo (not real args) in runtime . 

I need get function statement from name specified as Qore function `[namespace::][class::]method/function[([params*])]`.

We have `qore_root_ns_private::runtimeFindFunction` but I'm not sure about namespace vs. class and mainly how to convert arguments to paramTypeInfo in runtime.

```
#Input string examples:
myfunc
myns::myfunc
myvarfunc(string, int)
myvarfunc(hash)
myclass::mymethod
myns::myclass::mymethod
myclass::myvarmethod(hash)
myclass::myvarmethod(list)
```

**Comment by tmandys** [comment]
How to parse string to get name (with/without class/namespace) and arg list accepted by runtimeFindXXX ?
When no variant how to find function (i.e. just by name), name of runtimeFindExactVariant seems it requires exact arglist ? Extension of ql_misc.qpp functionType(string name) function could demonstrate proper usage.

**Comment by davidnich** [comment]
note to self: implement another function that returns all variants from a name with a list of hashes with the following keys:
* name: a string with the name as given in the search call
* desc: the description of the function/method - so the name and all arguments
* params: a list of parameter types

**Comment by davidnich** [comment]
@tmandys has this issue been addressed for the debugger?  If so, please close, if not, please comment on what's outstanding

**Comment by tmandys** [comment]
See _qore/test/qore/classes/Program/program.qtest_ where are commented out not working and marked as TODO, i.e. _findFunctionVariants()_ does not return statement:

- _Test::constructor_
- _Test::destructor_
- resolved function from inherited class
