### ISSUE TITLE
Unexpected behavior of delete operator when applied to primitive types

### ISSUE THREAD

**Issue by tethal** [qorelanguage/qore#187]
According to [documentation](http://qore.org/manual/current/lang/html/data_type_declarations.html#int_type), primitive types such as `int` should never contain NOTHING. However, the delete operator allows this:

```
int i = 5;
delete i;
printf("%N\n", i);
```

Produces:

```
<NOTHING>
```

But the variable is still treated as int as far as overload resolution is concerned:

```
sub x(nothing y) {
  printf("Nothing version\n");
}

sub x(int y) {
  printf("Int version\n");
}

int i = 5;
x(i);
delete i;
x(i);
```

Produces:

```
Int version
unhandled QORE System exception thrown in TID 1 at 2015-11-26 08:57:01.731856 Thu +01:00 (CET) at test5.q:14
RUNTIME-TYPE-ERROR: parameter 1 ('y') expects type 'int', but got nothing instead
```

This check would not be necessary in run-time if Qore guaranteed that int is always int, leading to major optimization opportunities at compile-time.

Compare to:

```
*int i = 5;
x(i);
delete i;
x(i);
```

Which produces:

```
Int version
Nothing version
```

**Comment by davidnich** [comment]
directly related to #488
