### ISSUE TITLE
hash arithmetics with a number silently passes

### ISSUE THREAD

**Issue by pavelkveton** [qorelanguage/qore#1942]
```
$ qore -X "100 + ('foo' : 1) + 10" 
110
```
this causes the errors to be silently "ignored", like in this one:
```
    t.update( ("status" : "E",
               "i_sepl_status" : "C",
              ),
              ("status" : op_in("I", "L"),
               "i_sepl_updated_id" : wfiid,
               "message_type" : "IT_OIC_INV_MSG_FDB",
               "email_fdb_cnt" : op_gt(sepl_getconf("aruba_retry_count", 12)) - 1,
              )
            );
```
The "-1" after op_gt means that the `where` condition finally equals to
```
"email_fdb_cnt" : -1,
```
which is valid, but completely different from the original meaning, and NOBODY notices.

I consider this worth (at least) creating a parse option to avoid the arithmetics between `hash` and `int` (or `number`), and maybe let's review (and avoid) the other options.

Targetting to 0.8.13, let's discuss.

**Comment by davidnich** [comment]
@pavelkveton  I believe this is a duplicate - already covered under #489 and #166 which cover this issue in a more general sense - if you agree, please close this as a duplicate
