### ISSUE TITLE
gethostbyname() should be replaced with getaddrinfo()

### ISSUE THREAD

**Issue by pvanek** [qorelanguage/qore#1952]
a warnign from buildservice

```
[  132s] qore.x86_64: I: binary-or-shlib-calls-gethostbyname /usr/lib64/libqore.so.0.8.13
[  132s] The binary calls gethostbyname(). Please port the code to use getaddrinfo().
```

refs. 
https://stackoverflow.com/questions/10346194/how-to-use-getnameinfo-instead-of-gethostbyname
http://blog.erratasec.com/2015/01/you-shouldnt-be-using-gethostbyname.html#.WUJqu63-g0k
etc.

**Comment by davidnich** [comment]
note that we already have the C++ `QoreAddrInfo` class, so we can use that to replace this call

**Comment by omusil24** [comment]
Is `gethostbyaddr()` used anywhere in Qore? If yes, then it would probably be good to also replace it with `getnameinfo()`.
