### ISSUE TITLE
module-oracle: implement non-blocking I/O for opening or closing a connection

### ISSUE THREAD

**Issue by davidnich** [qorelanguage/qore#197]
to ensure that the operation will either complete normally or be forced to complete by the oracle driver

Oracle can sometimes wait indefinitely when closing a connection, blocked on socket reads in the OCI library

for more info on the problem:
https://twiki.cern.ch/twiki/bin/view/PSSGroup/OCIClientHangProtection

**Comment by tethal** [comment]
There does not seem to be a way to programmatically enforce a timeout for opening a connection - I created a dummy server which accepts a connection but does not do anything and OCIServerAttach() just keeps waiting. Calling OCIBreak() from another thread succeeds, but it has no effect on OCIServerAttach(). Setting OCI_ATTR_NONBLOCKING_MODE to true before OCIServerAttach() fails with ORA-03126: network driver does not support non-blocking operations.
The only way I found is to set SQLNET.OUTBOUND_CONNECT_TIMEOUT in sqlnet.ora, which AFAIK cannot be done programmatically.

**Comment by tethal** [comment]
Closing a connection involves two calls: OCISessionEnd and OCIServerDetach. The second call simply sends 0000000A062000000040 and immediately closes the socket - it does not seem to be waiting for anything. The OCISessionEnd sends 0000000D062000000000030906 and waits for a response. Postponing this response resulted in the client being blocked. Calling OCIBreak from another thread succeeds, but the main threads still keeps waiting for the response. After it is received, the OCISessionEnd() call fails with ORA-01013: user requested cancel of current operation. Setting OCI_ATTR_NONBLOCKING_MODE does not seem to have any effect.
