### ISSUE TITLE
astparser cannot be built on Solaris due to the lack of strndup()

### ISSUE THREAD

**Issue by davidnich** [qorelanguage/qore#2027]
```
src/ast_scanner.lpp: In function 'char* make_cast(const char*)':
src/ast_scanner.lpp:172:36: error: 'strndup' was not declared in this scope
make[2]: *** [modules/astparser/CMakeFiles/astparser.dir/ast_scanner.cpp.o] Error 1
```

**Comment by niclasr** [comment]
There is now a branch named fix/missing-strndup that has a possible fix for this.
@davidnich you can try and build that branch on your solaris to see if it works. 
I don't have any OS around me without strndup to try on. I have tried and it builds on systems with strndup.

**Comment by davidnich** [comment]
@niclasr thank you very much - I will try to try it soon - the main problem is that our only solaris box is an old and very loud system that we try to only turn on when nobody's around to hear it - I may also be able to try a solaris VM somewhere online...

**Comment by omusil24** [comment]
Thanks for your work @niclasr, but I'm afraid it's not necessary to have two additional files added. Since it's one call, it can be simply fixed by using `memcpy()`. Hope you don't mind :)
