### ISSUE TITLE
module-astparser: please implement single compilation unit support

### ISSUE THREAD

**Issue by davidnich** [qorelanguage/qore#2050]
the astparser module is very slow to compile without single compilation unit support.

The main reason that the single compilation unit compiles are much faster is that when each c++ file is compiled separately, all the Qore headers need to be parsed and compiled for each file.

Currently the astparser module takes near 25s on my laptop to compile; I believe that with single compilation unit support, it could be just a couple of seconds max.

**Comment by omusil24** [comment]
You don't seem to be using multi-job building. It's much faster that way... It's also just a couple of seconds that way.

**Comment by davidnich** [comment]
```
david@quasar:~/src/qore/git/qore/build$ rm -rf modules/astparser/
removed 'modules/astparser/ast_parser.cpp'
...
david@quasar:~/src/qore/git/qore/build$ time make -j9 astparser
-- Found POSIX Threads: TRUE
-- ICONV_LIBRARY_TYPE is GNU libiconv
...
19 warnings generated.
[ 98%] Linking CXX shared library astparser-api-0.20.qmod
[100%] Built target astparser

real	0m26.606s
user	1m42.245s
sys	0m6.357s
```

I'm using a non-debug build (`cmake -DSINGLE_COMPILATION_UNIT=1 -DCMAKE_BUILD_TYPE=Release ..`).

So pretty please?  With a cherry on top?

**Comment by omusil24** [comment]
#2051
