### ISSUE TITLE
Allow selected tests only to be run by run_tests.sh

### ISSUE THREAD

**Issue by geckon** [qorelanguage/qore#2081]
It would be quite easy and beneficial (IMO) to add a simple option to `run_tests.sh` that would make the script run only selected test directories.

Something like this:

```
# run all the tests
run_tests.sh

# run only tests for Util module (path based on ./examples/test)
run_tests.sh -d qlib/Util

# the same result as previous example (path based on $PWD)
run_tests.sh -D ./examples/test/qlib/Util

# it can also be possible to run multiple test directories
run_tests.sh -d qlib/Util -d qlib/CsvUtil
```

The last example (i.e. multiple options) is just a proposal and we can live without that IMO. 

The option(s) can use different letter(s) and I can implement both `-d` and `-D` or just one of them if both were considered confusing together. Or neither of course if you don't think we don't need this. But I think it can be useful e. g. when working on a particular module to be able to just run the relevant tests quickly.

**Comment by pvanek** [comment]
qore tests/qlib/Util/*.qtest as a workaround?

**Comment by geckon** [comment]
As likely as not there is some issue on my side but `qore examples/test/qlib/Util/*.qtest` doesn't work for me.

Either way `./run_tests.sh -d qlib/Util` seems more user friendly to me.

**Comment by geckon** [comment]
I implemented `-d` option in branch feature/2081_select_tests, feel free to take a look. As of now it doesn't support multiple `-d` options (it will only run the last specified).

I'm open to suggestions as well as scratching this idea completely if it's not popular ;)

**Comment by omusil24** [comment]
`for t in examples/test/qlib/Util/*.qtest; do qore $t; done`

**Comment by geckon** [comment]
I added support for multiple `-d` options and created PR. Or is it something you'te not interested in at all? Thanks for comments.
