### ISSUE TITLE
regex_extract issue (likely an endless loop)

### ISSUE THREAD

**Issue by gamato** [qorelanguage/qore#2083]
While this works as expected:
```
$ qore -X 'regex_extract (" qaz\n\twsx\n\t edc", "(^[ \t]*)", Qore::RE_MultiLine + Qore::RE_Global)'
list: (3 elements)
  [0]=" "
  [1]="	"
  [2]="	 "
```
The following never finishes:
```
$ qore -X 'regex_extract ("qaz\n\twsx\n\t edc", "(^[ \t]*)", Qore::RE_MultiLine + Qore::RE_Global)'
```
Note the missing space char in the searched string.
It breaks if any leading whitespace is removed there (e.g. `" qaz\n\twsx\nedc"`).

**Comment by omusil24** [comment]
There's no need for the `^` character there...

**Comment by gamato** [comment]
What do you mean?  Without `^` it would match whitespace in any place, while I want to match it only at the beginning of lines.  But that's not the point here anyway.  The point is that our `regex_extract()` runs into an infinite loop.  And yes, it fails without `^` too, maybe even in more cases.

**Comment by gamato** [comment]
Btw, it's not about whitespace either, it gets stuck easily with any other characters. :-/
