### ISSUE TITLE
implement auto type to allow any type to be assigned and maintain all complex types

### ISSUE THREAD

**Issue by davidnich** [qorelanguage/qore#2090]

**Comment by omusil24** [comment]
What's the difference between this and `any`?

**Comment by davidnich** [comment]
it's in the docs - `any` (and no type declaration at all which is equal to `any`) strips complex type information for backwards compatibility.  By using `auto` you allow any type to be assigned and for complex type information to be maintained.

Stripping complex type info with untyped or generic types (ex: `hash` or `list`) was a necessary step to allow complex types to be introduced universally in Qore without existing code.
