### ISSUE TITLE
chr() does not return a proper char when int value passed as string

### ISSUE THREAD

**Issue by gamato** [qorelanguage/qore#2097]
Although `chr()` accepts softint, passing an int value as a string, that is w/o explicit cast to int, results in an empty string returned.
```
$ qore -X 'chr(97)'
"a"
$ qore -X 'chr("97")'
""
```

**Comment by omusil24** [comment]
This is happening because there's an overlooad for the chr() function `string chr(any arg)` which simply returns `'\0'` string, and which is apparently given preference over the softint variant when string is passed as an argument.

**Comment by davidnich** [comment]
this will get fixed with #2103
