### ISSUE TITLE
module-xml: the WSDL module cannot parse WSDLs with attribute definitions in complexType descriptions, furthermore these cannot be serialized or deserialized

### ISSUE THREAD

**Issue by davidnich** [qorelanguage/qore#21]

**Comment by davidnich** [comment]
closed in 42e0dacb6250316d2b26cd8f549f3a046ba58871

**Comment by davidnich** [comment]
attributes are still not serialized or deserialized correctly

**Comment by tethal** [comment]
There seems to be an issue with attribute types:

xsd:

	<xs:attribute name="itemNumber" type="xs:int" use="required" />

output:

    ^attributes^ : hash: (1 member)
       itemNumber : \"2\"

**Comment by tethal** [comment]
A list element with a single item is not serialized or deserialized as a qore list:

Xsd:

    <xs:element name="receipts" type="arpm:receiptList" />
    <xs:element name="receipt" type="arpm:receipt" />
      
    <xs:complexType name="receiptList">
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="arpm:receipt" />
      </xs:sequence>
    </xs:complexType>

With two receipts:

    receipts : hash: (1 member)
      receipt : list: (2 elements)
        [0]=hash: (16 members)
        [1]=hash: (16 members)

With one receipt:

    receipts : hash: (1 member)
      receipt : hash: (16 members)

With no receipt at all I get

    "Exception: SOAP-SERIALIZATION-ERROR: Detail 'cannot serialize element \"receipts\" of type \"receiptList\" from a list because maxOccurs = 1'"

**Comment by davidnich** [comment]
fix has been merged, #67 has been opened to track the status of testing
