### ISSUE TITLE
Cannot use casted values as hashdecl initializer values

### ISSUE THREAD

**Issue by omusil24** [qorelanguage/qore#2101]
```
%new-style

public hashdecl X {
    string y;
}

any a = "test";

string b = "test";

# OK
hash<X> h1({
    "y": b
});

# not OK
hash<X> h2({
    "y": cast<string>(a)
});

# not OK
hash<X> h3({
    "y": cast<string>(b)
});
```

output:
```
omusil@giger:~$ qore test.q
unhandled QORE System exception thrown in TID 1 at 2017-08-29 15:01:02.578431 Tue +02:00 (CEST) at test.q:18
PARSE-EXCEPTION: reference to undefined class 'string'
chained exception:
unhandled QORE System exception thrown in TID 1 at 2017-08-29 15:01:02.578431 Tue +02:00 (CEST) at test.q:18
PARSE-EXCEPTION: cannot cast<> to type 'object'
chained exception:
unhandled QORE System exception thrown in TID 1 at 2017-08-29 15:01:02.578431 Tue +02:00 (CEST) at test.q:16-17
PARSE-EXCEPTION: hashdecl 'X' initializer value for key 'y' from initializer value has incompatible type 'object'; expecting 'string'; types may not be compatible at runtime
chained exception:
unhandled QORE System exception thrown in TID 1 at 2017-08-29 15:01:02.578431 Tue +02:00 (CEST) at test.q:23
PARSE-EXCEPTION: reference to undefined class 'string'
chained exception:
unhandled QORE System exception thrown in TID 1 at 2017-08-29 15:01:02.578431 Tue +02:00 (CEST) at test.q:23
PARSE-EXCEPTION: cannot cast<> to type 'object'
chained exception:
unhandled QORE System exception thrown in TID 1 at 2017-08-29 15:01:02.578431 Tue +02:00 (CEST) at test.q:21-22
PARSE-EXCEPTION: hashdecl 'X' initializer value for key 'y' from initializer value has incompatible type 'object'; expecting 'string'; types may not be compatible at runtime
```

Also, cannot use the plain `any` value as initializer value, but I assume that that's working as designed.

**Comment by davidnich** [comment]
this is the same as #2045

**Comment by omusil24** [comment]
I don't think so... Why accept a value of the right type and not accept a cast to the right type?

Also, those exceptions don't make any sense... `string` is not an undefined class but a built-in type, and the code is not trying to cast to type `object`... Only the last of the three exceptions makes sense.

**Comment by davidnich** [comment]
@omusil24 you are combining two issues - one is that `cast<>` should accept any type (it doesn't now) and the other is #2045 which has already been discussed

If you want to change this to only be about `cast<>`, then I agree that we should fix it.  If you want to talk about hashdecl initialization, then it's the same as #2045

**Comment by omusil24** [comment]
I'm ok with #2045, since for complex types the code could be complex etc...
But here, in this case, I'd say it's different because it's simply a difference between `string` value and `cast<string>` value. In both cases you already have the type information at parse time and therefore you could check those types. These are simple types, not complex types.

Also, those casts should be fixed if they don't allow any types. Is there an issue for it already or should I create a new one?

**Comment by davidnich** [comment]
> Also, those casts should be fixed if they don't allow any types. Is there an issue for it already or should I create a new one? 

That's then the only issue here, so you can reuse this one by renaming it (it has nothing to do with hashdecls) or you can close this and make another.

**Comment by omusil24** [comment]
Also, I'm arguing about this because of the original code that I'm writing.
```
public hashdecl DebugParams {
    string programPath;
    bool stopOnEntry;
}

# works
hash<DebugParams> params(cast<hash<DebugParams>>({
    "programPath": request.arguments.program,
    "stopOnEntry": request.arguments.stopOnEntry
}));

# doesn't work
hash<DebugParams> params({
    "programPath": cast<string>(request.arguments.program),
    "stopOnEntry": cast<bool>(request.arguments.stopOnEntry)
});
```
which just seems stupid and confusing, since in the first case runtime complex type check is done, but in the second case even simple type check can't be done.

**Comment by davidnich** [comment]
@omusil24 it's not ideal and can and should be fixed but note that using emotional language like "stupid and confusing" is not constructive when you're talking about someone else's work

**Comment by omusil24** [comment]
I'm not saying you are stupid. Just that a user of the language (unaware of any connection to Qorus and any backwards-compatibility) would think so. Since the two pieces of code do pretty much the same thing.

**Comment by davidnich** [comment]
@omusil24 I know you're not saying I'm stupid, however my point still remains - anyway - please proceed as you see fit - this can and should be fixed

**Comment by omusil24** [comment]
I'm closing this issue and creating another one for the broken casts since there's unrelated discussion here IMO. Just to not mix things up.
