### ISSUE TITLE
inconsistent push operator behaviour

### ISSUE THREAD

**Issue by gamato** [qorelanguage/qore#215]
$ qore -n -e 'list l = (1,2); printf("%n\n", l);'
list: (1, 2)

$ qore -n -e 'list l = (1,2); delete l; printf("%n\n", l);'
<NOTHING>

$ qore -n -e 'list l = (1,2); delete l; push l, 3; printf("%n\n", l);'
list: (3)

$ qore -n -e 'softlist l = (1,2); delete l; push l, 3; printf("%n\n", l);'
<NOTHING>

**Comment by tethal** [comment]
I assume that for the `*list` list type this is ok:

```
$ qore -n -e '*list l = (1, 2); delete l; push l, 3; printf("%n\n", l);'
<NOTHING>
```

since the default for `*list` is `NOTHING` and not an empty list.

However, for the `unshift` operator we get this:

```
$ qore -n -e '*list l = (1, 2); delete l; unshift l, 3; printf("%n\n", l);'
unhandled QORE System exception thrown in TID 1 at 2015-12-29 10:05:53.408376 Tue +01:00 (CET) at <command-line>:1
UNSHIFT-ERROR: first argument to unshift is not a list
```

which is a completely different inconsistency.

**Comment by tethal** [comment]
After discussion the exception produced by `unshift` seems reasonable so we will implement this for other list operators as well

**Comment by davidnich** [comment]
in order not to break backward compatibility, the runtime exceptions will only be thrown if `%strict-args` is in effect
