### ISSUE TITLE
Regex extract test RAM greedy

### ISSUE THREAD

**Issue by geckon** [qorelanguage/qore#2162]
Running "Regex extract test" (`./examples/test/qore/functions/regex_extract.qtest`) consumed all my RAM (I have 20 GB) and then was killed. Something is clearly wrong there.

```
=====================================
Running test (114/210): ./examples/test/qore/functions/regex_extract.qtest
-------------------------------------
cmdline: LD_PRELOAD=./lib/.libs/libqore.so ./.libs/qore ./examples/test/qore/functions/regex_extract.qtest 
-------------------------------------
QUnit Test "Regex extract test" v1.0
./run_tests.sh: line 165: 15672 Killed                  LD_PRELOAD=./lib/.libs/libqore.so ./.libs/qore ./examples/test/qore/functions/regex_extract.qtest
-------------------------------------
```

**Comment by geckon** [comment]
"Replace test" (`./examples/test/qore/functions/replace.qtest`) does the same thing. The only difference is that the RAM allocation is noticeably slower in this case.

**Comment by omusil24** [comment]
Cannot reproduce...

Probably caused by updated `regex_extract.qtest` (because of #2083) while using old Qore build for the test. Try building and installing the latest version of Qore and then test again.

**Comment by geckon** [comment]
Sorry, it seems you are right. It doesn't happen with a new build. This issue can be closed.
