### ISSUE TITLE
RUNTIME-TYPE-ERROR in WSDL.qm

### ISSUE THREAD

**Issue by honzamares** [qorelanguage/qore#2189]
I have a problem with test WSDL 

> unhandled QORE System exception thrown in TID 1 at 2017-09-19 09:31:41.885755 Tue +02:00 (CEST) in WebService::resolveType() (/usr/share/qore-modules/WSDL.qm:4217, user code)
> RUNTIME-TYPE-ERROR: <lvalue> expects type 'object<XsdSimpleType>', but got an object of class 'XsdBaseType' instead
>call stack:
>  5: WebService::resolveType() (/usr/share/qore-modules/WSDL.qm:4342, user code)
>  4: WebService::parseTypes() (/usr/share/qore-modules/WSDL.qm:4071, user code)
>  3: WebService::constructor() (/usr/share/qore-modules/SoapClient.qm:241, user code)
>  2: SoapClient::constructor() (./IT-35-INV_STOCK_SALES_RETURN-WINCASH-IN.qtest:245, user code)
>  1: Mip35WincashTest::constructor() (line -1, user code)

This is different problem than this
[https://github.com/qorelanguage/qore/issues/2064](url)

**Comment by davidnich** [comment]
@honzamares sorry I didn't know you were going to open an issue - I already opened #2190 to cover this
