### ISSUE TITLE
qore build breaks with newer ssl due to missing EVP_sha

### ISSUE THREAD

**Issue by niclasr** [qorelanguage/qore#22]
The EVP_sha function is missing in newer versions of openssl.
man pages: [future](https://www.openssl.org/docs/manmaster/crypto/EVP_DigestInit.html), [current release](https://www.openssl.org/docs/man1.0.2/crypto/EVP_DigestInit.html)
This breaks builds of qore. [build log](http://pkgsrc.geeklan.co.uk/reports/current/OpenBSD-current/20150919.1053/qore-0.8.11nb2/build.log)
Fixes for this might be to remove it or add a configure test to see if EVP_sha is available and only use it if the test succeeds (similar to what is done with the sha512 function).
How do you think it should be solved?

**Comment by davidnich** [comment]
I guess make a test for it and conditionally compile it. In this case there
should also be a HAVE_ constant for it as well I think - I have to check
how that works tomorrow

I would like to switch to cmake, and I appreciate your efforts there very
much btw

If you want to do out in cmake then I'll try to cover it tomorrow in
autotools

Thx
David

**Comment by niclasr** [comment]
The cmake stuff needed is only 
check_cxx_symbol_exists(EVP_sha openssl/evp.h HAVE_OPENSSL_SHA)
.
I can try to fix the source code changes and autotools stuff tomorrow if you don't want to waste your time on it.

**Comment by davidnich** [comment]
That would be great, thanks niclas

**Comment by niclasr** [comment]
Fixed in fc181070ad1afbf49af2e8fc968b97328d690a86
Closing.
