### ISSUE TITLE
Private:internal methods documentation missing

### ISSUE THREAD

**Issue by omusil24** [qorelanguage/qore#2213]
Documentation about the `private:internal` modifier/methods is missing from the "Classes" documentation and possibly also somewhere else.

**Comment by davidnich** [comment]
this is documented here for example:
https://docs.qore.org/qore-0.8.13/lang/html/qore_classes.html#private_methods

please reopen if there is a misunderstanding

**Comment by omusil24** [comment]
Ok... Guess I was looking at old documentation...
