### ISSUE TITLE
module-astparser: install directory is wrong

### ISSUE THREAD

**Issue by omusil24** [qorelanguage/qore#2237]
astparser module gets installed into version-specific binary module dir (ex. `/usr/lib/x86_64-linux-gnu/qore-modules/0.8.13`), while all the other binary modules get installed into `/usr/lib/x86_64-linux-gnu/qore-modules`

**Comment by davidnich** [comment]
@omusil24 this is an issue that I raised to fix this - because it's released with Qore it needs to go in the version-specific directory which was created for this purpose - we also discussed this, but probably I didn't communicate the issues claearly

**Comment by omusil24** [comment]
Ah, ok... Makes sense.
