### ISSUE TITLE
the RestClient module will fail with an obscure error message if no serialization modules can be found

### ISSUE THREAD

**Issue by pavelkveton** [qorelanguage/qore#225]
html -tSqlUtil.tag=../../SqlUtil/html -tMapper.tag=../../Mapper/html doxygen/qlib/Doxyfile.tmpl doxygen/qlib/Doxyfile.RestClient
unhandled QORE System exception thrown in TID 1 at 2015-12-07 09:40:05.310119 Mon -01:00 (GMT+1) in Program::parse() (/home/kveton/src/qore/git/qore/qlib/RestClient.qm:341, builtin code)
PARSE-TYPE-ERROR: no pseudo-method <list>.firstKey() can be found
call stack:
  3: Program::parse() (doxygen/qdx:110, builtin code)
  2: qdx::doModDx() (doxygen/qdx:52, user code)
  1: qdx::constructor() (line -1, user code)
chained exception:
unhandled QORE System exception thrown in TID 1 at 2015-12-07 09:40:05.310119 Mon -01:00 (GMT+1) in Program::parse() (/home/kveton/src/qore/git/qore/qlib/RestClient.qm:342-343, builtin code)
INVALID-OPERATION: left-hand side of the expression with the '.' or '{}' operator is type 'list' and so this expression will always return NOTHING; the '.' or '{}' operator only returns a value with hashes and objects
call stack:
  3: Program::parse() (doxygen/qdx:110, builtin code)
  2: qdx::doModDx() (doxygen/qdx:52, user code)
  1: qdx::constructor() (line -1, user code)
chained exception:
unhandled QORE System exception thrown in TID 1 at 2015-12-07 09:40:05.310119 Mon -01:00 (GMT+1) in Program::parse() (/home/kveton/src/qore/git/qore/qlib/RestClient.qm:343, builtin code)
PARSE-TYPE-ERROR: no pseudo-method <list>.keys() can be found
call stack:
  3: Program::parse() (doxygen/qdx:110, builtin code)
  2: qdx::doModDx() (doxygen/qdx:52, user code)
  1: qdx::constructor() (line -1, user code)
chained exception:
unhandled QORE System exception thrown in TID 1 at 2015-12-07 09:40:05.310119 Mon -01:00 (GMT+1) in Program::parse() (/home/kveton/src/qore/git/qore/qlib/RestClient.qm:346, builtin code)
INVALID-OPERATION: left-hand side of the expression with the '.' or '{}' operator is type 'list' and so this expression will always return NOTHING; the '.' or '{}' operator only returns a value with hashes and objects
call stack:
  3: Program::parse() (doxygen/qdx:110, builtin code)
  2: qdx::doModDx() (doxygen/qdx:52, user code)
  1: qdx::constructor() (line -1, user code)
chained exception:
unhandled QORE System exception thrown in TID 1 at 2015-12-07 09:40:05.310119 Mon -01:00 (GMT+1) in Program::parse() (/home/kveton/src/qore/git/qore/qlib/RestClient.qm:346, builtin code)
PARSE-TYPE-ERROR: lvalue for assignment operator (=) expects type 'hash', but right-hand side is no value
call stack:
  3: Program::parse() (doxygen/qdx:110, builtin code)
  2: qdx::doModDx() (doxygen/qdx:52, user code)
  1: qdx::constructor() (line -1, user code)
chained exception:
unhandled QORE System exception thrown in TID 1 at 2015-12-07 09:40:05.310119 Mon -01:00 (GMT+1) in Program::parse() (/home/kveton/src/qore/git/qore/qlib/RestClient.qm:713, builtin code)
INVALID-OPERATION: left-hand side of the expression with the '.' or '{}' operator is type 'list' and so this expression will always return NOTHING; the '.' or '{}' operator only returns a value with hashes and objects
call stack:
  3: Program::parse() (doxygen/qdx:110, builtin code)
  2: qdx::doModDx() (doxygen/qdx:52, user code)
  1: qdx::constructor() (line -1, user code)
chained exception:
unhandled QORE System exception thrown in TID 1 at 2015-12-07 09:40:05.310119 Mon -01:00 (GMT+1) in Program::parse() (/home/kveton/src/qore/git/qore/qlib/RestClient.qm:715, builtin code)
PARSE-TYPE-ERROR: no pseudo-method <list>.keys() can be found
call stack:
  3: Program::parse() (doxygen/qdx:110, builtin code)
  2: qdx::doModDx() (doxygen/qdx:52, user code)
  1: qdx::constructor() (line -1, user code)
make: **\* [doxygen/qlib/Doxyfile.RestClient] Error 3

**Comment by pavelkveton** [comment]
the same finally happens when doing make html

**Comment by davidnich** [comment]
also docs cannot be built - will fail with the above error

**Comment by pavelkveton** [comment]
btw: this problem manifested itself due to incorrect qore setup on my laptop (the qore itself installed with different installation prefix than the modules), which caused the modules unreachable. If all the modules are properly found, the problem (naturally) disappears. So it was not top priority - nevertheless, it was still a bug.
