### ISSUE TITLE
lazy evaluated slicing

### ISSUE THREAD

**Issue by martin-zemek** [qorelanguage/qore#2260]
This does not seem really consistent:
```
map $1, "abcdefghijkl"[5..9] = ("f", "g", "h", "i", "j")
map $1, "abcdefghijkl"[1,5..9] = "bfghij"
```
or:
```
foldl $1 + "*" + $2, "abcdefghijkl"[5..9] = "f*g*h*i*j"
foldl $1 + "*" + $2, "abcdefghijkl"[1,5..9] = "bfghij"
```
Also, with lists:
```
map $1, (10,11,12,13,14,15,16,17,18)[1,4,5,6,7] = (11,14,15,16,17)
map $1, (10,11,12,13,14,15,16,17,18)[1,4..7] = (11,(14,15,16,17))
map $1, (10,11,12,13,14,15,16,17,18)[4..7] = (14,15,16,17)   # not nested lists like in previous case

```

**Comment by davidnich** [comment]
@martin-zemek this needs to be fixed ASAP before people start using it and we break working code due to a bad design in the initial release - let's please discuss a timeline tomorrow

**Comment by martin-zemek** [comment]
The point actually is in the expression like `1,4..7` that evaluates to `(1,(4,5,6,7))`. Which is correct if such an expression stands alone because the comma operator is supposed to create a list with any mixed kinds of elements.

But if such an expression is inside square brackets it should behave like simple flattened list. The non-lazy evaluation implementation actually does this flattening. But the lazy evaluation implementation does not.

**Comment by omusil24** [comment]
IMO expressions like this `var[1,5..9,8,23]` are really confusing anyway and I would get rid of them completely. Either use single range `var[5..9]` or a list of indices `var[1,8,23]`. Mixing them together is just unreadable.

**Comment by martin-zemek** [comment]
But there can in fact be whatever as an index - if it's not a list then it is cast to integer, e.g.:
`(0,1,2,3,4,5)["3asdf", ('b': 12), 2] = (3, 0, 2)`

**Comment by omusil24** [comment]
Yes, but obviously it's broken and left in only because of backwards compatibility.

**Comment by davidnich** [comment]
@omusil24 as just discussed with @martin-zemek offline, deferencing a list with `[]` must be done with:
* an integer value
* a range of integer values which will be interpreted to mean all the indexes in that range
* a list of integer values and possibly ranges which means all the indexes given

so strings and lists do not make sense for dereferencing a list with the `[]` operator

**Comment by gamato** [comment]
@omusil24 Expressions like `var[1,5..9,8,23]` seem very OK to my eyes and might be very handy and I'm pretty sure I've seen them elsewhere.

**Comment by gamato** [comment]
Regarding flattening, obviously it should be done as is already the case with non-lazy evaluation. Unflattened list does not make much sense in this case, does it.
