### ISSUE TITLE
debugger: once a stopped program receives a "go", further "stop" commands are ineffective

### ISSUE THREAD

**Issue by davidnich** [qorelanguage/qore#2281]
steps to reproduce:
* set a program context: `pgm <id>`
* add it as a debug target: `pgm add`
* set the program to stop when a thread is active: `pgm stop`
* make a call in the program - then the control transfers to the debugger
* start the program again: `go`

after this point, further calls to `pgm stop` appear to succeed but do not result in the program being stopped when a call is made to the program.

**Comment by davidnich** [comment]
cannot reproduce - maybe was a user error....

**Comment by tmandys** [comment]
It sounds as the program was detached when "go" or terminated before second "pgm stop". The first "go stop" is not needed, should stop when try to attach after "pgm add". TODO: auto-attach without stop (handy in case when program has plenty of threads)
