### ISSUE TITLE
add API to independently report results from internal code validation phases

### ISSUE THREAD

**Issue by gamato** [qorelanguage/qore#230]
It would be useful to have an API to differentiate between (two) validation phases of Qore code.
The syntax validation is important when loading stuff into Qorus, while errors from the 2nd phase could be ignored.

**Comment by tethal** [comment]
There's [Program::parsePending](http://qore.org/manual/current/lang/html/class_qore_1_1_program.html#a9afe5b8571dae845c49cd1f5f40c3722) which does the first parse phase.
