### ISSUE TITLE
module-astparser: missing support for ranges in the astparser module

### ISSUE THREAD

**Issue by davidnich** [qorelanguage/qore#2309]
ex `l[0..2]` is highlighted as a syntax error - the astparser scanner and parser are missing support for ranges implemented in 0.8.13

**Comment by pvanek** [comment]
how hard would be to merge both versions of scanner/parser to only one?

**Comment by davidnich** [comment]
@pvanek this is a general task that @omusil24 has already, let's check when he's back online

**Comment by omusil24** [comment]
Already got a fix for this and the latest debug directives. Just didn't have time to merge it before leaving Czech Rep...

@pvanek simple answer: hard... It would be easier and a better solution to just rewrite the current runtime structure somehow to get it generated from the scanned AST tree and therefore completely getting rid of the old parser/scanner than to try and merge those two parsers into one.
