### ISSUE TITLE
Swagger module can't handle integer/float info object version

### ISSUE THREAD

**Issue by omusil24** [qorelanguage/qore#2338]
example:
```
swagger: '2.0'
info:
  description: some API
  version: '1.0'
  title: Lorem Ipsum API
  contact:
    email: abc@xyz.com
```

throws: `INVALID-FIELD-TYPE: Info Object: "version" field has invalid type "float"; expecting "string"`

**Comment by davidnich** [comment]
@omusil24 is this with a yaml or json schema file?  could it be due to incorrect yaml or json deserialization of the schema file?

**Comment by omusil24** [comment]
YAML... Not sure. The `'1.0'` got transformed into float when parsing. Not sure if it's a feature of libyaml or it's a bad setting or maybe trying to be smart on the part of Qore.

**Comment by omusil24** [comment]
fixed in #2339

**Comment by omusil24** [comment]
Also `'+420777000666'` got parsed into an integer... Or well, anything number-like in the apostrophes. I had to put normal quotes (`"`) around these kind of strings to be interpreted as a string.

**Comment by davidnich** [comment]
looks like a yaml deserialization issue then:
```
david@quasar:~/src/qore/git/qore/src$ qore -l yaml -nX 'parse_yaml("'1234'").type()'
"integer"
```

that should be parsed as a string.   I would rather fix this definitively in the yaml module rather than work around it in the Swagger module

**Comment by davidnich** [comment]
currently we support yaml 1.1: http://yaml.org/spec/1.1/ 
and single-quoted strings should be deserialized as string values
