### ISSUE TITLE
HandleRequest headers are too case sensitive when forcing own format

### ISSUE THREAD

**Issue by tmandys** [qorelanguage/qore#2340]
When `HttpServer::handleRequest()` tries to force own output body (non-HTMLized) then hdr must contain "_Content-Type_" in this form even HTTP headers are not case sensitive (RFC). So using e.g.

_"Content-type": "text/plain",_ leads to "_cannot force: HTTP-HEADER-ERROR: multiple "content-type" headers received in HTTP message_"

Also I did not find this feature in docs (https://qoretechnologies.com/manual/qorus/latest/qore/modules/HttpServerUtil/html/class_http_server_1_1_abstract_http_request_handler.html#aa7c3c63fac5687bf2c9ea336157a2fc4)

**Comment by davidnich** [comment]
@tmandys thanks for opening this issue - I think we should fix it in the qore library in fact; to ensure case-insensitive uniqueness of headers as per https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2
