### ISSUE TITLE
parser error where )( is treated like ()

### ISSUE THREAD

**Issue by martin-zemek** [qorelanguage/qore#2394]
This works:

```
date)(
(6,5,4,3).first)(
("a":4, "b":3).keys)(
```

**Comment by davidnich** [comment]
@martin-zemek can you please improve the description?

**Comment by martin-zemek** [comment]
The description cannot be better.

**Comment by davidnich** [comment]
@martin-zemek I beg to differ.  nice bug though

**Comment by martin-zemek** [comment]
The bug actually "works" only on the command line, not in a script.

Observation (not yet a solution): if in the following code in `command-line.cpp` we remove from the string `str` the parentheses surrounding `eval_arg` (which is the input string for `qore -X`)  the bug will no longer work:
```
if (eval_arg) {
    QoreString str("printf(\"%N\\n\", (");
    str.concat(eval_arg);
    str.concat("));");
    qpgm->parse(str.getBuffer(), "<command-line>", &xsink, &wsink, warnings);
}
```
After removal:
```
if (eval_arg) {
    QoreString str("printf(\"%N\\n\", ");
    str.concat(eval_arg);
    str.concat(");");
    qpgm->parse(str.getBuffer(), "<command-line>", &xsink, &wsink, warnings);
}

```
