### ISSUE TITLE
Cross references for SftpPoller.qm don't work correctly

### ISSUE THREAD

**Issue by alachata-qore** [qorelanguage/qore#24]
See SftpPoller constructor in SftpPoller.qm

**Comment by pvanek** [comment]
What's cross reference in SftpPoller.qm? Where to find it in constructor's?

**Comment by davidnich** [comment]
Adrian means actually in the HTML documentation generated by docxygen - the references from the SftpPoller module to the ssh2 module docs weren't working on his computer.

However it looks like it's a doxygen issue on his machine - I just built the docs, and they worked fine (cross-references were intact) - I'll check it with Adrian tomorrow.

**Comment by davidnich** [comment]
was an environment issue
