### ISSUE TITLE
disable warning with g++ 7+

### ISSUE THREAD

**Issue by davidnich** [qorelanguage/qore#2449]
this warning becomes an error when compiled with `-Werror`
```
/home/david/src/qore/git/qore/include/qore/ScopeGuard.h:116:7: error: mangled name for ‘ScopeGuardImpl1<void (*)(void*) throw (), char*>::ScopeGuardImpl1(const ScopeGuardImpl1<void (*)(void*) throw (), char*>&)’ will change in C++17 because the exception specification is part of a function type [-Werror=noexcept-type]
 class ScopeGuardImpl1 : public ScopeGuardImplBase
       ^~~~~~~~~~~~~~~
```

**Comment by omusil24** [comment]
Wouldn't it be better to refactor the code so this problem doesn't happen instead of just ignoring the warning?

**Comment by davidnich** [comment]
@omusil24 this is not something you can solve with refactoring.  The warning is there because the ABI will change with C++17 because the exception specification in the function will be included in the mangled function name.  The exception specification is necessary and should not be removed.  We should change `throw()` -> `noexcept` as recommended by C++11, but the warning is still there with g++ >= 7

**Comment by omusil24** [comment]
Ok. Thanks for the explanation.
