### ISSUE TITLE
best to find new FreeBSD ports mainainer for lang/qore

### ISSUE THREAD

**Issue by 357r4bd** [qorelanguage/qore#2488]
It's not that I don't have the interest, it's an issue of time. And you guys deserve to have updated ports on FreeBSD. I think Qore and it's supporting modules are a real winners on FreeBSD. I just can't dedicate the time to get you there.

The best starting point is what's in Ports now. I can offer some general insight into the process, but the documentation is really good AND the process seems to change each time I do it - this is one of the only ports I maintain, so I have no real reason to keep up on it.

I would suggest getting the more useful modules up on Ports, like the DB support, REST framework, etc. It will encourage adoption. Thanks, Brett

**Comment by davidnich** [comment]
@estrabd no problem, Brett, thank you for all your efforts so far

**Comment by 357r4bd** [comment]
https://www.freshports.org/search.php?query=qore&search=go&num=10&stype=name&method=match&deleted=excludedeleted&start=1&casesensitivity=caseinsensitive

https://svnweb.freebsd.org/ports/head/lang/qore/

https://www.freebsd.org/doc/en/books/porters-handbook/port-upgrading.html

**Comment by 357r4bd** [comment]
In the past, my workflow has been to get a FreeBSD box (or VM) with the lastest RELEASE, update ports (via portsnap), and start with the contents of /usr/ports/lang/qore.

**Comment by davidnich** [comment]
@estrabd thank you again, Brett, maybe someone in the BSD community will get interested in Qore and want to do this some day

**Comment by 357r4bd** [comment]
Okay, that's up to you. I am not removing the port or requesting to be removed as maintainer, I just don't want to feel like I am holding qore back on FreeBSD. I'll get around to updating it at some point, I am sure.
