### ISSUE TITLE
Type conversions not according to documentation

### ISSUE THREAD

**Issue by tethal** [qorelanguage/qore#25]
According to [documentation](http://qore.org/manual/current/lang/html/operators.html#division_operator), strings should be converted to _numbers_, but they seem to be converted to _floats_:

```
printf("%y\n", 4 / 2.2n);         # gives 1.818181818181818181818181818181818181814
printf("%y\n", 4 / "2.2");        # gives 1.81818182
```

(Tested with version 0.8.12, git hash: 2ee5c954b5c88e6e56f0435b9ad75dcb5c324e73)

**Comment by davidnich** [comment]
let's fix the docs and generally support implicit conversions to a float instead of a number since it's more efficient and let users use numbers only explicitly since they're expensive

**Comment by tethal** [comment]
These should be explained somehow as well:

```
$ qore -n -X 'number(0.1)'
0.10000000000000001
$ qore -n -X '0.1 + 1e20n'
100000000000000000000.1000000000000000099
$ qore -n -X '0.1 + 1e30n'
1000000000000000000000000000000.1
$ qore -n -X '0.1 + 1e40n'
10000000000000000000000000000000000000000.100000000000000010003
$ qore -n -X '0.1 + 1e100n'
10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000.100000000000000010000000000000000000000085004940396
```

**Comment by gamato** [comment]
And perhaps it should be noted in docs even more that simple use cases like `exp2(16)` will actually execute `number exp2(number)` version of the function.

**Comment by davidnich** [comment]
@tethal the issue with the excess output is a result of the rounding heuristic - maybe we should try to improve the algorithm; current it requires 9 or 15 consecutive `0`s or `9`s before it decides that the rest is noise...

**Comment by davidnich** [comment]
docs have been corrected
