### ISSUE TITLE
extend QUnit.qm to provide info about number/float invisible differences

### ISSUE THREAD

**Issue by tmandys** [qorelanguage/qore#2556]
When `assertEq` complains that numeric value are not equal than provides confusing info.

**Comment by omusil24** [comment]
There are already functions for comparing floats and numbers: `assertFloatEq()`, `assertNumberEq()`
Both have been added in cc3999e3823769e06d21b158e994252ff662d927

**Comment by tmandys** [comment]
So the _assertEq, testAssertionValue,..._ with overloaded parameters should be defined. It is impossible use e.g. _CheckDbTableRows_ now for NUMERIC field.

**Comment by davidnich** [comment]
@tmandys has this issue been closed with the recent merge of your pull request?

Also please put `refs #<issue-id-number` in each commit message so we can cross-reference commits on the issues themselves.

**Comment by tmandys** [comment]
Yes, ii was closed in recent pull request

**Comment by davidnich** [comment]
@tmandys thank you; when you close an issue, please add the resolution label: `fixed`, `notabug`, or `wontfix`, thx
