### ISSUE TITLE
user modules - packges: to allow to write user modules in multiple files, organized in directory structure

### ISSUE THREAD

**Issue by pvanek** [qorelanguage/qore#2562]
https://bugs.qoretechnologies.com/projects/qorus/wiki/QoreModules

**Comment by petrycta** [comment]
**Done. Time spent: 5WD
Current solution:**


**Definitions:**
MainModule - MyModule.qm
Class - SomeClass.qc
Function - SomeFunction.ql

A module could be represented as a directory that consist MainModule(named as directory) and other Classes/Functions
**Ex:** 
MyModule/
_-MyModule.qm
-SomeClass.qc
-SomeFunction.ql_

MyModule.qm should implicitly include all Classes/Functions it uses (e.g. #include SomeClass.qc)
Single Class/Function could be included in any place it needed by using ModuleDirectoryName.SomeClassName.qc syntax (e.g. MyModule.SomeClass.qc)
