### ISSUE TITLE
Unintuitive declaration of multiple variables

### ISSUE THREAD

**Issue by tethal** [qorelanguage/qore#26]
list l1, l2;                       # error, statement has no effect
    my list l1, l2;                    # error, statement has no effect
    list (l1, l2);                     # multiple errors - l1, l2 undeclared, call to list() ignores retval
    my list (l1, l2);                  # error, local var 'list' declared as a function call
    (list l1, l2);                     # error, statement has no effect
    my (list l1, l2);                  # OK, but l2 is any

(Tested with version 0.8.12, git hash: 2ee5c954b5c88e6e56f0435b9ad75dcb5c324e73)

**Comment by davidnich** [comment]
ok for now - Qore's rules are a little different but are consistent - maybe can improve later?
