### ISSUE TITLE
Qore does not complain about unused function parameters

### ISSUE THREAD

**Issue by martin-zemek** [qorelanguage/qore#2646]
This is no problem (with `%enable-all-warnings`):

```
int sub unused_params(int m, int n, int p) {
    return 2 * n;
}
```
(Though there would be complaint about unused `q` here:
```
int sub unused_args(int m, int n, int p) {
    int q = 12;
    return 2 * n;
}
```
)

**Comment by martin-zemek** [comment]
Actually, we probably don't want to change (fix) this behavior because there are situations when we can't avoid having unused parameters.

For example, in mappers when a field is mapped by means of a code, the prototype must be `sub(any, hash)` but quite often the first parameter is not used.

**Comment by davidnich** [comment]
not going to fix - would break too much existing code - also it's normal for parameters to be declared and then ignored - either because the signature must match some existing signature, or because the params are for future use
