### ISSUE TITLE
Awkward creation of an empty list of type list<string>

### ISSUE THREAD

**Issue by martin-zemek** [qorelanguage/qore#2647]
If we want to call
`sub f(list<string> names) {...}`
with an empty list of `names` we cannot write simply
`f(())` .
We have to write
`f(cast<list<string>>(()));`
or
`f(new list<string>());`

(Or we have to give the argument a name - either by creating it advance:
```
list<string> no_names();
f(no_names);
```
or by creating it in place:
`f(list<string> no_names());`
)

**Comment by tmandys** [comment]
This is general empty list assignment to a typed list issue. Surprisingly it works with "??" workaround

```
    list<hash<CallStackInfo>> testCSI() {
        list<hash<CallStackInfo>> csi;
        #csi = ();   PARSE-TYPE-ERROR: lvalue for assignment operator '=' expects list<hash<CallStackInfo>>, but right-hand side is type 'list'
        return csi ?? ();

```
