### ISSUE TITLE
module-json: date serialization timezone (make_json())

### ISSUE THREAD

**Issue by pvanek** [qorelanguage/qore#2655]
```
qore -l json -X 'make_json(now_us())'
```

results in

```
2018-02-23 12:23:19.496213 +01:00
```

There is no problem with first space between date and time, but there is also a space between time and timezone. ISO 8601 requires no space between time and TZ

**Comment by omusil24** [comment]
Correct format should be `2018-02-23T12:23:19.496213+01:00`, i.e. `T` instead of the first space and no space before the timezone.
