### ISSUE TITLE
awkward immediate hashdecl value generation

### ISSUE THREAD

**Issue by davidnich** [qorelanguage/qore#2675]
it takes a lot of typing to generate an immediate typed hash value - programmers have to use either `new hash<XXX>({})` or `cast<hash<XXX>>({})` (where `XXX` is the hashdecl name).

I would like to propose a simpler syntax as follows: `XXX@{}`, for example:
```
const MyStatInfo = StatInfo@{"size": 20};
```

No spaces would be permitted between the identifier, the `@` and the `{`

**Comment by tmandys** [comment]
I would personally allow general (non-empty) hash to typed hash assignment with runtime check if all source fields are defined in hashdecl. If not then raise exception. But it seems unrealistic.

I will personally hate any operator requiring copypasting hashdecl name when makes no sense typecast to other type. So I would introduce a typeless syntax where the type is implicitly target type. What about reuse "auto" idea.

```
MyStatInfo = cast<auto>(("size": 20));   # better 
MyStatInfo = auto ("size": 20);    # operator
hash h.size = 23;
hash<StatInfo> si;
si += auto h; 

or 
si = cast h;   # if it can be parsed together with cast<>()

```

**Comment by davidnich** [comment]
@tmandys it may be possible to allow for immediate hashes to be recognized as type-compatible with a typed hash at parse time in the future, but it will take some work on the type system - it is not possible to do safely at the moment, at least I can't think of a way to do it right now without changing the type system.

The only way `cast<auto>` or an `auto` operator could work would be either 1) to remove all type information and push all type checking to runtime, which is the opposite of what I'd like to do, or 2) implement the type changes as per above which would anyway eliminate the need of an `auto` operator (since it would work automatically anyway).

So I believe we will be able to do what you want, and it would be good for Qore, but it will take some time to do probably.

**Comment by omusil24** [comment]
I'm ok with this but I have another suggestion. What about the following syntax?
```
const MyStatInfo = <StatInfo>{"size": 20};
```
To make it more aligned with other complex type usage.

**Comment by martin-zemek** [comment]
I would prefer @omusil24 's proposal for the syntax.

**Comment by davidnich** [comment]
@omusil24 @martin-zemek the same trivial scanner/parser trick works with this syntax as well:
```
david@greybeard:~/src/qore/git/qore/src$ qore -nX '<StatInfo>{"size": 2}.fullType()'
"hash<StatInfo>"
```

I'm happy with this too...

**Comment by sejvlond** [comment]
Ondra's syntax makes sense to me, also I want to point out the difference between ``hash()`` and ``new hash<Decl>()`` where the ``new`` is mandatory.
```
auto x = {};               # possible; hash
auto x = hash();           # possible; hash
auto x = new hash();       # impossible

auto x = <Decl>{};         # now possible; hash<Decl>
auto x = hash<Decl>();     # impossible
auto x = new hash<Decl>(); # possible; hash<Decl>
```

If the second case would be possible to use ``auto x = hash<Decl>();`` I wouldn't need the shortcut.

**Comment by davidnich** [comment]
@omusil24 @sejvlond @martin-zemek @tmandys I implemented support for both styles - i.e.:
```
auto x = <Decl>{};
auto x = hash<Decl>{};
```

With implicit initialization (construction) and the possibility to override the members in the curly brackets.  Note that also the second variant requires curly brackets, and there can be no spaces in the text before the open curly bracket.

Please review the pull request below - assigned to @pvanek for merging:
https://github.com/qorelanguage/qore/pull/2695
