### ISSUE TITLE
qpp: unable to access AbstractDatasource classes (AD, D, DP) in any qpp file

### ISSUE THREAD

**Issue by pvanek** [qorelanguage/qore#2678]
errors like:
error: ‘QC_ABSTRACTDATASOURCE’ was not declared in this scope
etc.

**Comment by davidnich** [comment]
it's not exported by the library; to export it, add definitions in QoreClass.h like:
```
DLLEXPORT extern qore_classid_t CID_ABSTRACTDATASOURCE;
DLLEXPORT extern QoreClass* QC_ABSTRACTDATASOURCE;
```

Then this class can be used in qpp files in binary modules - it can go in 0.8.13.3 for example - it's a trivial change.

**Comment by pvanek** [comment]
sure, this issue is for tracking
