### ISSUE TITLE
Variable declaration in the middle of an expression

### ISSUE THREAD

**Issue by tethal** [qorelanguage/qore#27]
The fact that variable declaration is considered an expression can lead to potentially confusing behavior:

    printf("%y\n", 1 ? (my x = 3) : (my y = 4));    # prints 3
    printf("x: %y\n", x);                           # prints x: 3
    printf("y: %y\n", y);                           # prints y: null

Both `x` and `y` are declared but only x is initialized. Also:

    printf("%y\n", (my x = 3) || (my y = 4));       # prints True
    printf("x: %y\n", x);                           # prints x: 3
    printf("y: %y\n", y);                           # prints y: null

(Tested with version 0.8.12, git hash: 2ee5c954b5c88e6e56f0435b9ad75dcb5c324e73)

**Comment by davidnich** [comment]
behavior is consistent - so let's leave it
