### ISSUE TITLE
fractional seconds are not handled correctly with ISO-8601 relative date/time values

### ISSUE THREAD

**Issue by davidnich** [qorelanguage/qore#2721]
ex:
```
david@greybeard:~/src/qore/git/qore/examples/test/qore/vars$ qore -nX 'date("P1YT1H0.1S")'
<time: 1 year 1 hour 1 second>
```

**Comment by omusil24** [comment]
Also module-yaml is exporting them in incorrect format.
Instead of `PT1.23456S`, it's `PT1S23456u`, which does not conform to the standard.

Also2, it seems that module-json does not handle relative dates at all and exports them in datetime format...

**Comment by davidnich** [comment]
@omusil24 yes we need to fix that in the yaml module - this change will allow us to align the yaml module closer with the ISO-8601 standard
