### ISSUE TITLE
WebUtil.qm: TextTemplateBase::add() use Program::parse() instead of parsePending() + commit

### ISSUE THREAD

**Issue by pvanek** [qorelanguage/qore#2742]
unfortunately it's in static method add(), which is used in many places in qore and qorus (probably). The parse commit should go everywhere (maybe)

{reason: "/usr/share/qore-modules/0.9.0/WebUtil.qm:243: PARSE-ERROR: parsing can only happen once for each Program container", who: null, source: null, info: null}

**Comment by davidnich** [comment]
maybe we can change the implementation to use `parsePending()`  and then `parseCommit()` implicitly on the first use if not performed explicitly with a new `commit()` method for example
