### ISSUE TITLE
Catch clause ignores variable type

### ISSUE THREAD

**Issue by tethal** [qorelanguage/qore#28]
Variable `x` in the catch block behaves as if it were declared as `any`:

    try {
        throw 1;
    } catch (string x) {
        printf("%y\n", x);
        x = 123;
    }

(Tested with version 0.8.12, git hash: 2ee5c954b5c88e6e56f0435b9ad75dcb5c324e73)

**Comment by davidnich** [comment]
let's fix so that the catch blocks only accept a hash declaration (or no type if that's legal for the current parsing context) and enforce any type declarations

**Comment by tethal** [comment]
Type of the exception variable is currently optional, even with `%require-types`

```
try {
} catch (x) {
}
```

We should make this illegal, (but implement a new parse option that enables it).
