### ISSUE TITLE
Statements don't always issue a parse error when having no meaning as a whole (but their subexpressions have effect)

### ISSUE THREAD

**Issue by omusil24** [qorelanguage/qore#2826]
```
#!/usr/bin/env qore
# -*- mode: qore; indent-tabs-mode: nil -*-

%new-style
%enable-all-warnings
%require-types
%strict-args

string a = "abcd";
a == a.substr(0, a.size()-1);
```

**Comment by martin-zemek** [comment]
1. When a statement has no meaning as a whole but the expression contains a function call that in itself has effect (possibly only can throw an exception) no error is issued:

```
qore -ne '12.3 + 45;'                  # ok  - error 'statement has no effect'
qore -ne 'round(12.3) + 45;'           # bug - error ignored
qore -ne '"zxcv";'                     # ok  - error 'statement has no effect'
qore -ne 'substr("zxcv", 2);'          # bug - error ignored
qore -ne '"asdf" + "zxcv ";'           # ok  - error 'statement has no effect'
qore -ne '"asdf" == "zxcv ";'          # ok  - error 'statement has no effect'
qore -ne 'rtrim("zxcv ");'             # ok  - error 'return value is ignored'
qore -ne '"asdf" + rtrim("zxcv ");'    # bug - error ignored
qore -ne 'int(5);'                     # ok  - error 'return value is ignored' (int(int) has no effect)
qore -ne 'int("5");'                   # bug - error ignored (int(string) has effect - can throw an exception)
```

2. In some cases when a statement has no meaning as a whole and the expression contains a function call that also has no effect in itself still no error is issued:
`qore -ne '1 + int(5);'                     # bug - error ignored
`

3. In some cases when a statement has no meaning as a whole and the expression contains a function call that also has no effect in itself wrong parse error is issued:
`qore -ne '"asdf" == rtrim("zxcv ");'   # bug  - wrong error message: 'return value of rtrim is ignored'`

**Comment by davidnich** [comment]
related to #2747
