### ISSUE TITLE
error in opensuse RPM spec file

### ISSUE THREAD

**Issue by vyskocilm** [qorelanguage/qore#2861]
openSUSE Tumbleweed, packages from home:davidnichols. Package `qore-stdlib` requires `libcore` as a dependency, however on openSUSE name is `libcore5`.

**Comment by pvanek** [comment]
@davidnich is it fine for you to change it in your repo?

**Comment by davidnich** [comment]
@pvanek yes it's been fixed in the build service; updated packages are now available
