### ISSUE TITLE
Parser does not recognize that a return value is NOT ignored if the returned value is an object and its method is immediately called

### ISSUE THREAD

**Issue by martin-zemek** [qorelanguage/qore#2863]
Example (in QUnit.qm):
`get_thread_data("tc").incAssertionsOk();`

If get_thread_data() was correctly flagged as `CONSTANT` the above code would issue a warning that the call `get_thread_data("tc")` has no side effects and its return value is ignored. The current version of qore "solves" this problem by a hack consisting in that the function in flagged only with `RET_VALUE_ONLY` (functions with this flag currently don't issue that warning).

As a part of #2826 there is a new warning implemented also for the cases when a function does not have side effects except that it may throw an exception and the return value is ignored. This corresponds to the flag `RET_VALUE_ONLY` (having no side effects and not throwing exceptions corresponds to the flag `CONSTANT`). For the above code example to work also with the new warnings this issue need to be fixed. The fix will be part of #2826.

(And in the end, when this is issue is fixed the flag of get_thread_data() can be changed to CONSTANT.)

**Comment by davidnich** [comment]
For the method call above a warning should not be executed no matter how the `get_thread_data ()` function is flagged because the warning should be on the expression as a whole, i.e. including the method call.

**Comment by martin-zemek** [comment]
Yes, exactly.

The solution is in `QoreDotEvalOperatorNode::parseInitImpl()`:
Instead of
`left = left->parseInit(oflag, pflag, lvids, typeInfo);`
there will be
`left = left->parseInit(oflag, pflag & ~PF_RETURN_VALUE_IGNORED, lvids, typeInfo);`

**Comment by martin-zemek** [comment]
This issue has been fixed along with #2826
