### ISSUE TITLE
Inconsistent scope of local variables

### ISSUE THREAD

**Issue by tethal** [qorelanguage/qore#29]
The scope of variables declared in e.g. an `if` statement is to the end of that statement, as if the whole statement was in curly braces:

    if (my s = "b") {
        my s = "c";
        print(s);              # c
    } else {
        print(s);              # b
    }
    print(s);                  # error, s undeclared

But not entirely, the following behaves as if the statement was not in curly braces:

    my s = "a";
    if (my s = "b") {          # error, s already declared
        ...
    }
    print(s);                  # a

Note that similar code is legal in C++. In Qore, explicit statement block needs to be used:

    my s = "a";
    {
        if (my s = "b") {      # OK
            print(s);          # b
        }
    }
    print(s);                  # a

(Tested with version 0.8.12, git hash: 2ee5c954b5c88e6e56f0435b9ad75dcb5c324e73)

**Comment by davidnich** [comment]
since Qore's behavior is consistent, let's leave it like this
