### ISSUE TITLE
Separate Qore module loadings

### ISSUE THREAD

**Issue by petrycta** [qorelanguage/qore#2966]
### Idea: to have an ability to structure complex modules into multiple files.
**Curret status:**
_One-File-One module_
**Proposed Qore Implementation:**
    _One-File-Modules_

### Implemented as directories.
```html
MyModule/
    MyModule.qm - a file with the same name as the base directory has. It contains standard module headers as in single file module. It does or it doesn't contain any public symbols (namespaces, classes, functions...)
    Class1.qc - imported automatically into QoreProgram
    functions.ql - imported automatically into QoreProgram
```

For more details see [wiki](https://bugs.qoretechnologies.com/projects/qorus/wiki/QoreModules)

Estimated time: ~5WD
Spent time: 3WD

**Comment by omusil24** [comment]
Duplicate of #2562

**Comment by petrycta** [comment]
closed as duplicate
