### ISSUE TITLE
FsUtil: Add fileExists() and getFileContent()

### ISSUE THREAD

**Issue by petrycta** [qorelanguage/qore#2998]
Please add to FxUtil.qm next functions:
fileExists(filePath)
getFileContent(filePath)

**Comment by geckon** [comment]
@petrytar, what should `getFileContent()` do? Get the text/binary content, read the whole file to memory and return? Open the file and return the file object? Something else? Thanks.

**Comment by petrycta** [comment]
In case I need, it should read whole file as text to memory and return it. But it would be nice to have some arg to decide how to read the file. But David currently refers me that `ReadOnlyFile::readTextFile()` or `ReadOnlyFile::readBinaryFile()` are do it. And FileInputStream for big files

**Comment by geckon** [comment]
Yes, those functions already exist. So I suppose only file_exists would be needed but for that there is `Qore::is_file()` function - https://docs.qore.org/current/lang/html/group__filesystem__functions.html#ga6117e36222d08c197c2c0de1cadea715

So I think we can close this issue? Or is there anything you still miss, @petrycta? Thanks

**Comment by petrycta** [comment]
@geckon no, thank you. Nice solution )
