### ISSUE TITLE
CRLF gets converted to LF when reading from stdin in Windows

### ISSUE THREAD

**Issue by omusil24** [qorelanguage/qore#3061]
Found in Qore 0.8.13.7 downloaded from https://github.com/qorelanguage/qore/releases/download/release-0.8.13.7/qore-0.8.13.7-windows.zip

test.q:
```
# -*- mode: qore; indent-tabs-mode: nil -*-

%require-types
%enable-all-warnings
%new-style
%strict-args

string out = stdin.read(10);
binary bin = binary(out);
stderr.printf("%s\n", bin.toHex());
```

output:
```
$ printf "a\r" | xxd -p
610d

$ printf "a\n" | xxd -p
610a

$ printf "a\r\n" | xxd -p
610d0a

$ printf "a\r" | qore test.q
610d

$ printf "a\n" | qore test.q
610a

$ printf "a\r\n" | qore test.q
610a
```

**Comment by omusil24** [comment]
Same thing happens when reading from `stdin_stream`.

**Comment by omusil24** [comment]
Might be caused by MinGW (GCC) or MSYS or Windows standard library in general.

https://sourceforge.net/p/mingw/mailman/message/8686966/
http://mingw.5.n7.nabble.com/Problem-with-GCC-not-outputting-cr-lf-for-Windows-td19982.html

**Comment by pvanek** [comment]
internal note: possible showstopper for trainings on windows

**Comment by davidnich** [comment]
there is a trivial fix for this using `_setmode()`: https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/setmode?view=vs-2017

```
printf "a\r\n" | ./qore.exe ../tmp/test.q
610d0a
```

**Comment by davidnich** [comment]
pull request here: https://github.com/qorelanguage/qore/pull/3066
verified fixed on Windows

**Comment by omusil24** [comment]
@davidnich Doesn't this problem affect also reading from/writing to regular files? There is no option to use binary mode when creating/opening `File` or `ReadOnlyFile`.

**Comment by davidnich** [comment]
> Doesn't this problem affect also reading from/writing to regular files? There is no option to use binary mode when creating/opening File or ReadOnlyFile.

@omusil24 no, this already worked - it only needed to be fixed with the `std*` constants - `O_BINARY` is automatically set on regular files on Windows unless `O_TEXT` is used in the `File` or `ReadOnlyFile` constructor

**Comment by omusil24** [comment]
IMO Qore user should be able to set this manully like with all the other options. Something like `O_BINARY` and `O_TEXT` would be good.

**Comment by davidnich** [comment]
> IMO Qore user should be able to set this manully like with all the other options. Something like O_BINARY and O_TEXT would be good.

@omusil24 that's what I was trying to say in my comment above - that's how it works already, so there's nothing to fix AFAIK

**Comment by omusil24** [comment]
The documentation doesn't say anything about these constants - https://docs.qore.org/current/lang/html/group__file__open__constants.html

**Comment by davidnich** [comment]
> The documentation doesn't say anything about these constants

OK right, Qore doesn't have them - they are only usable on Windows, and if you pass the integer value of `O_TEXT` as a flag, it will be respected, but there is no `O_TEXT` constant in Qore, that's correct.  

I guess that should be fixed in another issue - is it needed at the moment for parsing on Windows?

**Comment by omusil24** [comment]
No, it's not.
