### ISSUE TITLE
qore compilation warnings: warning: 'visibility' attribute ignored [-Wattributes]

### ISSUE THREAD

**Issue by pvanek** [qorelanguage/qore#3091]
We are receiving tons of the same messages during compilation:
```
[ 1449s] [ 93%] Building CXX object modules/reflection/CMakeFiles/reflection.dir/QC_Class.cpp.o
[ 1449s] In file included from /home/abuild/debbuild/BUILD/qore-9.99/include/qore/Qore.h:78:0,
[ 1449s]                  from /home/abuild/debbuild/BUILD/qore-9.99/build/modules/reflection/qore_reflection.h:36,
[ 1449s]                  from /home/abuild/debbuild/BUILD/qore-9.99/build/modules/reflection/QC_Class.cpp:31:
[ 1449s] /home/abuild/debbuild/BUILD/qore-9.99/include/qore/ExceptionSink.h:336:35: warning: 'visibility' attribute ignored [-Wattributes]
[ 1449s]      DLLLOCAL QoreProgramLocation* loc;
[ 1449s]                                    ^~~
```

warnings are silenced with this patch:

```
pvanek@spongebob:~/src/qore/qore (develop *$%=)> git diff
diff --git a/include/qore/ExceptionSink.h b/include/qore/ExceptionSink.h
index 47df851cb..b04a0d12e 100644
--- a/include/qore/ExceptionSink.h
+++ b/include/qore/ExceptionSink.h
@@ -333,7 +333,7 @@ private:
     std::string source_str;
 
     // actual exception location
-    DLLLOCAL QoreProgramLocation* loc;
+    QoreProgramLocation* loc;
 };
 
 #endif
```

is it fine to apply this one?

**Comment by pvanek** [comment]
@davidnich @sejvlond opinions?

**Comment by sejvlond** [comment]
I don't know, not familiar with `DLLLOCAL` :(

**Comment by davidnich** [comment]
@sejvlond `DLLLOCAL` marks the symbol to not be exported in the library's ABI

@pvanek the class backed by this member is private; why do you want to remove this?  also removing is not technically correct, symbols in public headers should be either `DLLLOCAL` (not accessible from binary modules) or `DLLEXPORT` (accessible)

**Comment by pvanek** [comment]
I want to remove warnings. See eg. attached log
[log.txt](https://github.com/qorelanguage/qore/files/2561496/log.txt)

**Comment by davidnich** [comment]
@pvanek right, I did not get that warning; I guess you can't set symbol visibility on individual class members; please remove it, thx!

**Comment by omusil24** [comment]
If the other members don't have visibility set, then this one shouldn't either. Also, since it's ignored anyway, it should be removed.

Also, please look here @davidnich https://gcc.gnu.org/wiki/Visibility
On Windows, they use `__attribute__ ((dllexport))` and `__attribute__ ((dllimport))` for GCC. That's missing from `include/qore/common.h`.

**Comment by davidnich** [comment]
@omusil24 thanks for the info; if there is something to fix, please raise an issue with the details and ideally also make the fix, thx
