### ISSUE TITLE
Docs: hash minus operator does not modify the existing hash but returns a new one

### ISSUE THREAD

**Issue by geckon** [qorelanguage/qore#3110]
The [docs](https://docs.qore.org/current/lang/html/operators.html#minus_operator) says that the `-` operator deletes a key from the hash which is not entirely true. It in fact apparently creates and returns a new hash without the key in it.

```
$ qore -ne 'hash h = {"a": 2}; hash b = h - "a"; printf("%N\n", h);'
hash: (1 member)
  a : 2
```

**Comment by omusil24** [comment]
Obviously. That's how +/- etc. operators work. They don't change the operands in-place. They always produce a new result.

**Comment by omusil24** [comment]
For in-place modification, you can use the `-=` operator (https://docs.qore.org/current/lang/html/operators.html#minus_equals_operator).

**Comment by geckon** [comment]
I'm not saying that the behavior is wrong. I'm saying that the docs could be a bit more descriptive about that ;) It's an issue aiming to improve the docs, not to change the behavior.

**Comment by omusil24** [comment]
Ok, that makes sense. I wrote a clearer explanation here:

> However, if the left-hand side is a hash, and the right-hand side is a string, then the result will be a new hash with the hash key represented by the string removed. If the left-hand side is a hash and the right-hand side is a list, then a new hash will be produced and each element from the list will be converted to a string key and any hash item with a matching key will be deleted from the new hash. Having both left and right arguments hashes is an invalid operation which does not modify the hashes in any way and silently returns NOTHING.

If it's ok like that, please use it to modify the documentation and create a pull request.

**Comment by geckon** [comment]
@omusil24 sounds good, thanks.
