### ISSUE TITLE
FsUtil: add copy functions using only specific FS object types and depths

### ISSUE THREAD

**Issue by pvanek** [qorelanguage/qore#3121]
eg. to copy a tree without files, just with dirs.

to copy only a N levels of dirs

**Comment by geckon** [comment]
I can imagine a use case for a copy with dirs only or N levels only but move? Maybe my imagination is limited but is there any? What should it do with the rest (files or the rest of the levels)? Remove?

**Comment by davidnich** [comment]
> What should it do with the rest (files or the rest of the levels)? Remove?

@geckon I suggest encrypting the rest of the files with a hidden key and leaving a README in the directory with a bitcoin wallet code and a price for decryption

**Comment by pvanek** [comment]
Good point. Let's do copy only

**Comment by geckon** [comment]
Also it probably makes sense to do a dir_only but not files_only, right? Or do we want to e.g. copy all files in the source tree to the destination dir (with flat "structure")? Or maybe just copy the first level of files?

**Comment by pvanek** [comment]
Hmm, and what about the `find` multiplatform implementation?

**Comment by geckon** [comment]
@pvanek, not sure I follow. Do you mean unix `find`?

**Comment by pvanek** [comment]
Yes. Something like find. Give mě all dirs in a tree... All files. All files and dirs UP to level 3...

I am just thinking out loud

**Comment by geckon** [comment]
Still not sure how that is related to copying. Or do you want to find **and** copy them? We can do it, but what would structure would it create in destination if we only wanted to copy files (and not dirs)?

- flat structure?
- the same structure as in src? i.e. ignoring empty dirs and dirs below level N?
- something else?

**Comment by pvanek** [comment]
Not related. Just do copy:
- copy dirs only
- limit depth of subdir (also with and without files) 

I will open another issues for rest of ideas

**Comment by geckon** [comment]
I see, thanks.

**Comment by geckon** [comment]
I suggest to implement a new `copy_dir_structure(src, dst, *int depth)` method that will copy the specified number of levels (directories only). If no depth argument is provided, it will recreate the whole sctructure.

Is it OK, @pvanek?

Also this should somehow deal with symlinks and maybe have an overwrite parameter as well (if there is something in `dst`) but for simplicity reasons maybe it can ignore symlinks (it's meant for dirs anyway) and fail if there is something in `dst`, unless you have a use case for any of these..

**Comment by geckon** [comment]
merged with #3150
