### ISSUE TITLE
Operations on timeout data type behave strange

### ISSUE THREAD

**Issue by turlyalz** [qorelanguage/qore#3157]
This works as expected:
```
qore -ne 'timeout t = 3s; printf("%y\n", t); t = 1s; printf("%y\n", t);'
3000
1000
```

This works fine for now, but also can be changed in the way that it will automatically convert the '1s' to 1000 (because the timeout data type is integer and it holds milliseconds), probably can break something:
```
qore -ne 'timeout t = 3s; printf("%y\n", t); t -= 1s; printf("%y\n", t);'
3000
2999
```

But this is incorrect:
```
qore -ne 'timeout t = 3s; printf("%y\n", t); t = t - 1s; printf("%y\n", t);'
3000
2999000
```

The same behavior is for '+' operator.

**Comment by sejvlond** [comment]
well this is also weird
```
qore -ne 'timeout t = 3s; printf("%y\n", t); t -= 1s; printf("%y\n", t);'
3000
2999
```
timeout 3s - 1s is no 2999 ms...
