### ISSUE TITLE
refactor RootMap - do not store const char* without a copy

### ISSUE THREAD

**Issue by sejvlond** [qorelanguage/qore#3181]
1. Class RootMap at include/qore/intern/QoreNamespaceIntern.h#556
takes `const char *` as an argument of public `update` method and it stores it without copying it, there are no guaranties that the `const char *` will be valid when this method exits
```
template <typename T>
class RootMap : public std::map<const char*, NSOInfo<T>, ltstr> {
    DLLLOCAL void update(const char* name, qore_ns_private* ns, T* obj) {
        // get current lookup map entry for this object
        typename map_t::iterator i = this->find(name);
        if (i == this->end())
            this->insert(typename map_t::value_type(name, info_t(ns, obj)));
        else // if the old depth is > the new depth, then replace
            if (i->second.depth() > ns->depth)
                i->second.assign(ns, obj);
    }
```

2. instead of doing `find` and `insert` we can refactor for using [lower_bound](https://en.cppreference.com/w/cpp/container/map/lower_bound) and [emplace_hint](https://en.cppreference.com/w/cpp/container/map/emplace_hint), the performance would be significantly increased

3. using `const char *` as a key for a map means that all the comparison will be done for identity, comparing addresses, not comparing actual values

**Comment by davidnich** [comment]
@sejvlond addresses were not compared, as `ltstr` was used as the comparator arg in the template, the other issues have been addressed
