### ISSUE TITLE
Assignment operator precedence

### ISSUE THREAD

**Issue by tethal** [qorelanguage/qore#32]
The assignment operator `=` has higher precedence than the others (`*=`, `+=` etc.) which is unusual (in C they are all the same). The consequence is that the following is an error in Qore:

    int a = 1;
    int b = 2;
    a = b += 2;
    > PARSE-EXCEPTION: expecing lvalue for += operator expression, got 'assignment operator expression' instead
    
One has to use parentheses like this:   

    a = (b += 2);      # OK, a = 4, b = 4

(Tested with version 0.8.12, git hash: 2ee5c954b5c88e6e56f0435b9ad75dcb5c324e73)

**Comment by davidnich** [comment]
let's align qore to c if it doesn't break anything (to be verified)
