### ISSUE TITLE
Precedence of the comma operator

### ISSUE THREAD

**Issue by tethal** [qorelanguage/qore#33]
The [comma operator](http://qore.org/manual/current/lang/html/operators.html#comma_operator) is supposed to have [higher precedence](http://qore.org/manual/current/lang/html/operators.html) than assignment, but it works only in some cases.

    l = (10,);

    l += 3, 2;           # OK - (10, 3, 2)
    l += (3, 2);         # OK - (10, 3, 2)
    (l += (3, 2));       # OK - (10, 3, 2)
    (l += 3, 2);         # Error - statement has no effect

Another example where commas have lower precedence than assignment is an attempt to assign two variables at once:

    l1, l2 = 1, 2;       # error, statement has no effect
    l1, l2 = (1, 2);     # error, statement has no effect
    (l1, l2) = 1, 2;     # error, statement has no effect
    (l1, l2) = (1, 2);   # OK

Or:

    any l1 = any l2 = 6, 7, 8;          # both are [6, 7, 8]
    any l1 = list l2 = 6, 7, 8;         # both are [6, 7, 8]
    any l1 = (any l2 = 6, 7, 8);        # l1 = [6, 7, 8], l2 = 6
    any l1 = (list l2 = 6, 7, 8);       # PARSE-TYPE-ERROR: lvalue for assignment operator (=) expects type 'list', but right-hand side is type 'int'

The third and fourth lines are examples of the issue - parentheses break the special handling of assignment operator in the first element of a list, which can hurt if one is forced to use parentheses due to #32:

    any l1 = any l2 += 6, 7, 8;         # PARSE-EXCEPTION: expecing lvalue for += operator expression, got 'assignment operator expression' instead
    any l1 = list l2 += 6, 7, 8;        # PARSE-EXCEPTION: expecing lvalue for += operator expression, got 'assignment operator expression' instead
    any l1 = (any l2 += 6, 7, 8);       # l1 = [6, 7, 8], l2 = 6
    any l1 = (list l2 += 6, 7, 8);      # l1 = [[6], 7, 8], l2 = [6]

Here the errors in the first two lines are caused by #32; the results of lines 3 and 4 are unexpected.

(Tested with version 0.8.12, git hash: 2ee5c954b5c88e6e56f0435b9ad75dcb5c324e73)

**Comment by davidnich** [comment]
design error - will make the consistent behavior the default and implement a parse option to enable the broken list/comma-precedence handling with a warning + fix docs (to be verified...)
