### ISSUE TITLE
Relational operators with mixed types

### ISSUE THREAD

**Issue by tethal** [qorelanguage/qore#330]
It is not clear from the [documentation](https://qore.org/manual/current/lang/html/operators.html#logical_less_than_operator) how does comparison of different types work.

For example:

```
$ qore -n -X '"65536" < 65536n'
True
$ qore -n -X '65536.0 < 65536n'
True
$ qore -n -X '65536 < 65536n'
True
$ qore -n -X '65536 == 65536n'
True
$ qore -n -X '65536 <= 65536n'
False
```

May be related to #25

**Comment by tethal** [comment]
This has nothing to do with #25

```
$ qore -n -X '65536n <= 65536n'
False
$ qore -n -X '65536n < 65536n'
False
$ qore -n -X '65536n == 65536n'
True
$ qore -n -X '65536n > 65536n'
False
$ qore -n -X '65536n >= 65536n'
False
```

**Comment by davidnich** [comment]
there are bugs in expressions executed at parse time and substituted into the parse tree:

```
qore -ne 'number n = 1n; printf("%y\n", n >= 1n);'
True
```

whereas:

```
qore -nX '1n >= 1n'
False
```

I'm working on it.
