### ISSUE TITLE
Comparison <=> operator fails when comparing suffixes

### ISSUE THREAD

**Issue by tmandys** [qorelanguage/qore#3372]
qore -X '"20190412000000456000" <=> "20190412000000456"'
0

Note: in also in 0.8.13

**Comment by omusil24** [comment]
```
qore -X '"abc" <=> ""'
0
```

The comparison only compares the first x characters, where x is the length of the shorter string.

**Comment by davidnich** [comment]
fixed with the string comparison fixes
