### ISSUE TITLE
sort() doesn't work correctly for strings of different length

### ISSUE THREAD

**Issue by geckon** [qorelanguage/qore#3378]
This isn't right:

```
$ qore -nX 'sort(("hc", "h"))'
list: (2 elements)
  [0]="hc"
  [1]="h"
$ qore -nX 'sort(("h", "hc"))'
list: (2 elements)
  [0]="h"
  [1]="hc"
```

Maybe the different length isn't the defining property that connects these cases together but it seems to work properly if the strings have the same length.

**Comment by omusil24** [comment]
Python for comparison:
```
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> a = ("hc", "h")
>>> sorted(a)
['h', 'hc']
>>> a = ("h", "hc")
>>> sorted(a)
['h', 'hc']
```

**Comment by omusil24** [comment]
Gonna fix this and probably also gonna refactor the sorts since they're not commented and seem to use duplicated code and not the most efficient implementations.

**Comment by davidnich** [comment]
the comparison operators are also broken:
```
david@greybeard:~/src/qore/git/qore/src$ qore -nX '"a" < "ab"'
False
david@greybeard:~/src/qore/git/qore/src$ qore -nX '"a" > "ab"'
False
```

so there is a general problem comparing strings where the prefixes match but have different lengths

**Comment by omusil24** [comment]
Yeah, the problem was in the string comparison function. I already fixed it, but the tests failed because of some problem with the Oracle DB. Gonna look at it tomorrow.
