### ISSUE TITLE
Hash addition: confusing arithmetic with ?: operator

### ISSUE THREAD

**Issue by turlyalz** [qorelanguage/qore#3383]
The following code:
```
bool test = True;

hash res;
res += {
    "a": "test",
} + (test ? {"b": 1} : {});

printf("%N\n", res);
```
will print
```
hash: (2 members)
  a : "test"
  b : 1
```

But if we remove the parentheses in the `?:` operator:
```
bool test = True;

hash res;
res += {
    "a": "test",
} + test ? {"b": 1} : {};

printf("%N\n", res);
```
it will print
```
hash: (1 member)
  b : 1
```

**Comment by davidnich** [comment]
it's due to precedence rules - without parens it's equivalent to:
```
qore -ne 'bool test = True;

hash res;
res += ({
    "a": "test",
} + test) ? {"b": 1} : {};

printf("%N\n", res);
'
hash: (1 member)
  b : 1
```

**Comment by turlyalz** [comment]
@davidnich, ok, a little bit confusing for me, because what does the addition of bool value to a hash? Probably, not a bug, we can close the issue :)

**Comment by davidnich** [comment]
@turlyalz Qore's operator precedence was originally designed to mimic Perl's; here is Qore's:
https://docs.qore.org/current/lang/html/operators.html

and here is Perl's:
https://perldoc.perl.org/perlop.html#Operator-Precedence-and-Associativity

As you can see, for the two operators in question; `+=` and `? :`, the relative precedence is the same - `+=` has lower precedence than `? :`.

**Comment by turlyalz** [comment]
@davidnich, that's ok, I'm just wondering why this: ```{
    "a": "test",
} + test``` works, how the addition is applied?
