### ISSUE TITLE
build-break in QoreSquareBracketsOperatorNode when configured with --enable-debug --disable-single-compilation-unit

### ISSUE THREAD

**Issue by pavelkveton** [qorelanguage/qore#391]
libtool: compile:  g++ -DHAVE_CONFIG_H -I../include/qore -I../include -I../include -I../lib -DHAVE_UNIX_CONFIG_H -D_QORE_LIB_INTERN -DMODULE_DIR=\"/usr/local/lib/qore-modules\" -DMODULE_VER_DIR=\"/usr/local/lib/qore-modules/0.8.12\" -DUSER_MODULE_DIR=\"/usr/local/share/qore-modules\" -DUSER_MODULE_VER_DIR=\"/usr/local/share/qore-modules/0.8.12\" -DHAVE_UNIX_CONFIG_H -g -m32 -fno-strict-aliasing -D_THREAD_SAFE -pthread -Wall -lm -m32 -fno-strict-aliasing -D_THREAD_SAFE -pthread -Wall -MT QoreSquareBracketsOperatorNode.lo -MD -MP -MF .deps/QoreSquareBracketsOperatorNode.Tpo -c QoreSquareBracketsOperatorNode.cpp  -fPIC -DPIC -o .libs/QoreSquareBracketsOperatorNode.o
QoreSquareBracketsOperatorNode.cpp: In member function 'virtual AbstractQoreNode\* QoreSquareBracketsOperatorNode::parseInitImpl(LocalVar_, int, int&, const QoreTypeInfo_&)':
QoreSquareBracketsOperatorNode.cpp:55:6: error: incomplete type 'qore_program_private' used in nested name specifier
QoreSquareBracketsOperatorNode.cpp:71:6: error: incomplete type 'qore_program_private' used in nested name specifier
QoreSquareBracketsOperatorNode.cpp:88:6: error: incomplete type 'qore_program_private' used in nested name specifier
In file included from ../include/qore/intern/Function.h:43:0,
                 from ../include/qore/intern/QoreLibIntern.h:329,
                 from ../include/qore/Qore.h:222,
                 from QoreSquareBracketsOperatorNode.cpp:31:
../include/qore/intern/qore_value_list_private.h: At global scope:
../include/qore/intern/qore_value_list_private.h:49:22: warning: 'QoreListNode\* do_args(const QoreValue&, const QoreValue&)' defined but not used [-Wunused-function]

**Comment by tethal** [comment]
Fixed in #392
