### ISSUE TITLE
several basic PostgreSQL data types are not [correctly] supported in PgsqlSqlUtil

### ISSUE THREAD

**Issue by gamato** [qorelanguage/qore#415]

**Comment by davidnich** [comment]
please list the types explicitly - see #404 for an existing bug about the varbit type
also see the pgsql driver docs for types supported by the binary driver - PgsqlSqlUtil is limited by the types the binary driver supports

**Comment by gamato** [comment]
Right. Will do soon.

**Comment by gamato** [comment]
Fixed in #428 -- added and/or fixed support for the following datatypes and aliases: bool, float, int, timetz, timestamptz, varbit; bit, bit varying, char, character, character varying, oid, varchar.
