### ISSUE TITLE
Unpredictable order of member initialization

### ISSUE THREAD

**Issue by tethal** [qorelanguage/qore#42]
**Code:**

    class A {
        constructor(b) { printf("A constructor, b = %y\n", b); }
        destructor() { printf("A destructor\n"); }
    }
    
    class B {
        constructor() { printf("B constructor\n"); }
        destructor() { printf("B destructor\n"); }
    }
    
    class C {
        public {
            B b();
            A a(self.b);
        }
    }
    
    C c();

**Expected output:**

    B constructor
    A constructor, b = {<B object>}
    A destructor
    B destructor

**Actual output:**

    A constructor, b = null
    B constructor
    A destructor
    B destructor

**Note:**

Members should be initialized in the order of declaration and destroyed in the opposite order.
Also note that due to the unpredictability of the issue you may not be able to reproduce this exactly - in that case try changing the names of the member variables.

**Comment by tethal** [comment]
@omusil24 could we run Qorus regression tests with this new version please?

**Comment by omusil24** [comment]
@tethal Regression tests have been run without any problems.
