### ISSUE TITLE
segfault on syntax error

### ISSUE THREAD

**Issue by pavelkveton** [qorelanguage/qore#421]
[IT-90-EXPORT_USIM_OPTIONS.zip](https://github.com/qorelanguage/qore/files/94140/IT-90-EXPORT_USIM_OPTIONS.zip)

running the test file is fine, unless you change the line

```
    const REMOTE_TABLE = "ps_etlit_erp_codprod";
```

to

```
    const REMOTE_TABLE = "ps_etlit_erp_codprod",
```

(mark the last character change from semicolon to colon). The latter one produces a segfault, instead of some reasonable syntax error message.

Note that I had to zip the test file since github does not like .qtest suffix...

**Comment by tethal** [comment]
minimalistic example:

```
%new-style
class P {
  private { const X = string m; }
}
```

or with old style:

```
class P {
  private { const X = my string $m; }
}
```

Basically the issue is that we are declaring a local variable `m` which does not make sense.
