### ISSUE TITLE
recursive scans in deterministic garbage collection fail when closure-bound local variables point to objects in the recursive chain 

### ISSUE THREAD

**Issue by davidnich** [qorelanguage/qore#423]
in this case, the rcount is not calculated incorrectly (it's too low) and such objects are not collected resulting in memory leaks

**Comment by tethal** [comment]
Example:

```
%new-style
%enable-all-warnings
%require-types
%strict-args

class C {
    public {
        code c;
    }
}

sub f() {
    C c();
    c.c = sub() {print(c);};
}

f();
```

**Comment by davidnich** [comment]
the example above illustrates what's still missing - the solution in pull request #424 is only partial - scanning closures properly for recursive links though closures is not yet implemented.  Pull request #424  treats a closure like a container and scans it for object loops.  In the example above, the object is not collected because it's referenced strongly by a closure-bound local var (c), and the object is also referenced in the closure.  This type of recursive reference is not yet handled by the GC algorithm.
