### ISSUE TITLE
Some modules do not link on openSUSE

### ISSUE THREAD

**Issue by susnux** [qorelanguage/qore#4335]
Since #3802 libqore is not linked anymore for any module, this results in linker issues on openSUSE (see end of post).

The problem is, you are using `add_library(... MODULE ...)` but `QORE_BINARY_MODULE` (`_INTERN2`) will call

https://github.com/qorelanguage/qore/blob/f3d5fb4ff8ae642551de466993545222158a844e/cmake/QoreMacros.cmake#L190

This will cause issues on openSUSE as the `CMAKE_..._LINKER_FLAGS` are set like this:

```
DCMAKE_EXE_LINKER_FLAGS=-flto=auto -Wl,--as-needed -Wl,--no-undefined -Wl,-z,now
DCMAKE_MODULE_LINKER_FLAGS=-flto=auto -Wl,--as-needed
DCMAKE_SHARED_LINKER_FLAGS=-flto=auto -Wl,--as-needed -Wl,--no-undefined -Wl,-z,now
```

So `CMAKE_MODULE_LINKER_FLAGS` should not rely on `DCMAKE_SHARED_LINKER_FLAGS`.

---

Log:

> [   50s] /usr/bin/cmake -E cmake_link_script CMakeFiles/json.dir/link.txt --verbose=1
> [   50s] /usr/bin/c++ -fPIC -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -DNDEBUG -std=c++11 -DBUILDING_DLL=1 -O2 -g -DNDEBUG -Wl,--as-needed -Wl,--no-undefined -Wl,-z,now -Wl,-undefined -Wl,dynamic_lookup -shared  -o json-api-1.1.qmod CMakeFiles/json.dir/src/json-module.cpp.o CMakeFiles/json.dir/QC_JsonRpcClient.cpp.o CMakeFiles/json.dir/ql_json.cpp.o 
> [   50s] /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/json.dir/src/json-module.cpp.o: in function `json_module_init()':
> [   50s] /home/abuild/rpmbuild/BUILD/module-json-release-1.0.10/src/json-module.cpp:54: undefined reference to `QoreNamespace::addSystemClass(QoreClass*)'
> [   50s] /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/json.dir/src/json-module.cpp.o: in function `json_module_ns_init(QoreNamespace*, QoreNamespace*)':
> [   50s] /home/abuild/rpmbuild/BUILD/module-json-release-1.0.10/src/json-module.cpp:62: undefined reference to `QoreNamespace::copy(long long) const'
> [   50s] /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /home/abuild/rpmbuild/BUILD/module-json-release-1.0.10/src/json-module.cpp:62: undefined reference to `QoreNamespace::addNamespace(QoreNamespace*)'
> [   50s] /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/json.dir/src/json-module.cpp.o: in function `__static_initialization_and_destruction_0':
> [   50s] /home/abuild/rpmbuild/BUILD/module-json-release-1.0.10/src/json-module.cpp:51: undefined reference to `QoreNamespace::QoreNamespace(char const*)'

**Comment by davidnich** [comment]
@susnux thank you for this report - fixed in commit `57e4d116ca58297ccc4270eada28472c5fa9804e`
