### ISSUE TITLE
PgsqlSqlUtil cannot handle tables in schemas other than public in some cases

### ISSUE THREAD

**Issue by shev-vadim-net** [qorelanguage/qore#4602]
Hello. In our project we use [PostgreSQL Schemas](https://www.postgresql.org/docs/current/ddl-schemas.html) and face some issues with `SQLUtil` module.
Minimal steps to reproduce.
1. Create a Schema with tables:
```sql
CREATE SCHEMA test;
CREATE TABLE test.table1 (id INTEGER NOT NULL UNIQUE, name VARCHAR(255));
CREATE TABLE test.table2 (id INTEGER NOT NULL UNIQUE, parent_id INTEGER NOT NULL, CONSTRAINT fk_parent FOREIGN KEY (parent_id) REFERENCES test.table1(id));
```
2. Try to fetch rows from `test.table2`:
```
SqlUtil::AbstractTable table = getSqlTable(getDatasourcePool("DS name"), "test.table2");
logInfo("%N", table.selectRows());
```
Which produces the error like:
```
MAJOR: TABLE-ERROR: A Qore exception occurred, info: "datasource \"DS name\" (pgsql:...): datasource \"DS name\" (pgsql:...): cannot retrieve table information for table \"table1\" in \"pgsql:...\""
```
However running this works fine:
```
SqlUtil::Table table = new SqlUtil::Table(getDatasourcePool("DS name"), "test.table2");
logInfo("%N", table.selectRows());
```
Until we try to join 2 tables:
```
SqlUtil::Table table = new SqlUtil::Table(getDatasourcePool("DS name"), "test.table2");
logInfo("%N", table.selectRows({ "join": join_inner("test.table1") }));

# OR

SqlUtil::Table table = new SqlUtil::Table(getDatasourcePool("DS name"), "test.table2");
SqlUtil::Table table1 = new SqlUtil::Table(getDatasourcePool("DS name"), "test.table1");
logInfo("%N", table.selectRows({ "join": join_inner(table1) }));
```
Which produces the same error `...cannot retrieve table information for table \"table1\"...`.

What do you think?

**Comment by davidnich** [comment]
@shev-vadim-net please make sure your PostgreSQL user or role can access the system catalog `pg_catalog` - SqlUtil relies on this for introspection - i.e.:
```
grant select on all tables in schema pg_catalog to <user>;
```

**Comment by shev-vadim-net** [comment]
Hi @davidnich, on my local I log in with `postgres` user. As I know this is a superuser which has full access. But the error still appears.

It seems to me the `SqlUtil` tries to retrieve the table information from `public` schema ignoring the provided `test` schema.

**Comment by davidnich** [comment]
ok - I see - this is probably then the source of the problem - thanks for that info - will check it out and get back to you ASAP

**Comment by davidnich** [comment]
@shev-vadim-net  this is now fixed (not merged yet, but I have a test case like your code above in Qorus, and it's working now - also tables in datasource in other schemas are now enumerated by SqlUtil as <schema>.<tablename> when the schema is not `public`) - so please let me know how urgent you need the fix - I can make a release possibly as soon as tomorrow

**Comment by shev-vadim-net** [comment]
Hi @davidnich, that sounds great! For me it's not urgent, because for the time being I use the workarounds: `SqlUtil::Table` class instead of `UserApi::getSqlTable` and sub-query instead of `join`. But it's great to know the issue is already fixed and will be released soon. Thanks for looking into that!

**Comment by davidnich** [comment]
@shev-vadim-net note that the join will work with the fix, but because the unique constraint on `table1` is not a PK, you will have to provide the columns for the join in the join clause - ex:
```
prompt$ qore -l SqlUtil -ne '
Datasource ds("pgsql:omquser/omquser@omquser");
Table t1(ds, "test.table1");
Table t2(ds, "test.table2");
printf("%N\n", t2.selectRows({"join": join_inner(t1, "t1", {"id": "id"})}));'
list: (1 element)
  [0]=hash: (4 members)
    id : 1
    parent_id : 1
    id_1 : 1
    name : "test"
```
