### ISSUE TITLE
binary-or-shlib-calls-gethostbyname /usr/lib64/libqore.so.12.1.2

### ISSUE THREAD

**Issue by skriesch** [qorelanguage/qore#4680]
I have updated (and cleaned up the packaging logs) for qore.
We have got following message:

```
[  321s] libqore12.x86_64: W: binary-or-shlib-calls-gethostbyname /usr/lib64/libqore.so.12.1.2
[  321s] The binary calls gethostbyname. Please port the code to use getaddrinfo.
```

That can only be fixed in the upstream project.

**Comment by davidnich** [comment]
@skriesch Qore uses `getaddrinfo()` - Qore has a `gethostbyname()` function (in the Qore language), but the internal C++ implementation uses `getaddrinfo()`.  

I believe this must be a false positive.  You can check the object file or the library with `objdump -t` - there is no reference to an external or internal `gethostbyname()` function (but the external reference to `getaddrinfo()` is listed...)

**Comment by skriesch** [comment]
I have used _grep -r "gethostbyname" ._ on the archive and there is Qore::gethostbyname() available. That is correct.

Based on what will libqore.so.12.1.2 be built, that I can identify the correct library? The qore project has been growing in the last years. Sorry for such questions.

**Comment by davidnich** [comment]
If you mean which network library, it's internal - you can look at `QoreNet.cpp` and specifically the `QoreAddrInfo` class - the only network library used by Qore is libc.

**Comment by davidnich** [comment]
@skriesch I'm closing this, as I assume it's a false positive - please reopen with additional info if you think it's not - thanks for helping improve Qore's quality with bug reports!
