### ISSUE TITLE
Overload resolution with softX types

### ISSUE THREAD

**Issue by tethal** [qorelanguage/qore#47]
**Code:**

    sub f(softbool arg) {
        printf("Bool version: %N\n", arg);
    }
    sub f(softfloat arg) {
        printf("Float version: %N\n", arg);
    }
    sub f(softnumber arg) {
        printf("Number version: %N\n", arg);
    }
    sub f(softint arg) {
        printf("Int version: %N\n", arg);
    }
    f("5");

Which of the overloads should be called?

**Note:**

See #48

**Comment by davidnich** [comment]
this is ambiguous, let's try to avoid this - let's not fix this for now
