### ISSUE TITLE
NetBSD PowerPC build of qore does not use powerpc machine specific macros

### ISSUE THREAD

**Issue by niclasr** [qorelanguage/qore#4711]
The machine specific macros are not used when building qore on NetBSD with the PowerPC architecture leading to a build failure as can be seen in [build logs](http://ftp.ziaspace.com/pub/pkgsrc/reports/9.0_2022Q4/20230322.0656/qore-1.12.0/build.log) . I tracked this down to that NetBSD on PowerPC does not define __ppc or __ppc__ but only defines __powerpc__ so it is not catches by the "if defined" statement for the PowerPC macros. Fix coming up.

**Comment by davidnich** [comment]
thanks for this fix
