### ISSUE TITLE
qore 1.16.1 not compatible with qore-json and qore-yaml

### ISSUE THREAD

**Issue by skriesch** [qorelanguage/qore#4733]
I wanted to update qore in openSUSE. 

qore-yaml is failing with following error message now:
[   43s] + QORE_MODULE_DIR=:qlib
[   43s] + qore -l ./yaml-api-1.3.qmod test/DataStreamClient.qtest -v
[   43s] cannot load './yaml-api-1.3.qmod': failed to load module './yaml-api-1.3.qmod':
[   43s]  * <builtin>:-1: LOAD-MODULE-ERROR: error loading qore module '/home/abuild/rpmbuild/BUILD/qore-yaml-module-0.7.3/yaml-api-1.3.qmod': /home/abuild/rpmbuild/BUILD/qore-yaml-module-0.7.3/yaml-api-1.3.qmod: cannot open shared object file: No such file or directory
[   43s] please fix the errors listed above and try again.

qore-json has got an equal problem with the following error:
[   16s] + qore -l ./json-api-1.3.qmod test/JsonRpcClient.qtest -v
[   16s] cannot load './json-api-1.3.qmod': failed to load module './json-api-1.3.qmod':
[   16s]  * <builtin>:-1: LOAD-MODULE-ERROR: error loading qore module '/home/abuild/rpmbuild/BUILD/qore-json-module-1.8.2/json-api-1.3.qmod': /home/abuild/rpmbuild/BUILD/qore-json-module-1.8.2/json-api-1.3.qmod: cannot open shared object file: No such file or directory
[   16s] please fix the errors listed above and try again.

**Comment by davidnich** [comment]
@skriesch the bugs are in the spec files - the module api numbers are hardcoded in the lines that execute the tests instead of using the macro value - I've just pushed fixes to both modules - for example the fixes to the yaml module spec file looks like:
```
-qore -l ./yaml-api-1.3.qmod test/DataStreamClient.qtest -v
-qore -l ./yaml-api-1.3.qmod test/DataStreamHandler.qtest -v
-qore -l ./yaml-api-1.3.qmod test/DataStreamUtil.qtest -v
-qore -l ./yaml-api-1.3.qmod test/YamlRpcHandler.qtest -v
-qore -l ./yaml-api-1.3.qmod test/yaml.qtest -v
+qore -l ./yaml-api-%{module_api}.qmod test/DataStreamClient.qtest -v
+qore -l ./yaml-api-%{module_api}.qmod test/DataStreamHandler.qtest -v
+qore -l ./yaml-api-%{module_api}.qmod test/DataStreamUtil.qtest -v
+qore -l ./yaml-api-%{module_api}.qmod test/YamlRpcHandler.qtest -v
+qore -l ./yaml-api-%{module_api}.qmod test/yaml.qtest -v
```

Thanks for erporting this issue!
