### ISSUE TITLE
Compilation of lib/QoreEllipsesNode.cpp breaks in non-scu builds

### ISSUE THREAD

**Issue by niclasr** [qorelanguage/qore#4749]
Compilation of lib/QoreEllipsesNode.cpp breaks in non-scu builds with the message:
``lib/QoreEllipsesNode.cpp: In member function 'virtual int QoreEllipsesNode::parseInitImpl(QoreValue&, QoreParseContext&)':``
``lib/QoreEllipsesNode.cpp:42:27: error: incomplete type 'qore_program_private' used in nested name specifier
     qore_program_private::get(*getProgram())->makeParseException(*loc, "ILLEGAL-ELLIPSES",``

Solution: include qore/intern/qore_program_private.h in QoreEllipsesNode.cpp

**Comment by davidnich** [comment]
@niclasr fixed - thanks for the bug report!

**Comment by niclasr** [comment]
@davidnich it is a c++ issue ``#include "qore/intern/qore_program_private.h"`` is needed in QoreEllipsesNode.cpp
At least for me when using gcc 7 to compile.
