### ISSUE TITLE
Disallow out-of-line additions to classes and namespaces

### ISSUE THREAD

**Issue by tethal** [qorelanguage/qore#483]
It should not be possible to add members (methods or fields) to a class after its definition. 

Also, adding fields to existing instances should not be possible, but `%require-types` already enforces this.

Current behavior should be possible with a parse option.

**Comment by gamato** [comment]
Hmm, I thought this might be one of the features of dynamic languages.

**Comment by davidnich** [comment]
this will be addressed with #1179 with the addition of the `%strong-encapsulation` parse directive
