### ISSUE TITLE
Disallow deprecated returns clauses in function definitions

### ISSUE THREAD

**Issue by tethal** [qorelanguage/qore#485]
... but introduce a parse-options that enables them

```
sub x() returns int {
}
```

**Comment by gamato** [comment]
Just out of curiosity -- why to do it ?

I can imagine that some users may prefer this usage.

**Comment by tethal** [comment]
This has been considered [deprecated](https://qore.org/manual/develop/lang/html/qore_functions.html#function_return_types) for a long time. The [documentation of classes](https://qore.org/manual/develop/lang/html/qore_classes.html) does not even mention this possibility.
