### ISSUE TITLE
Default values for non-asterisk types: %strict-types

### ISSUE THREAD

**Issue by tethal** [qorelanguage/qore#488]
Implement a parse option that will change the default values of types so that a variable of a type without an asterisk is never evaluated to `NOTHING`, as it is [documented](https://qore.org/manual/develop/lang/html/data_type_declarations.html).

Note that some types do not have any default values - see #176 for an example.

(The motivation for this is to be able to implement ints as 64-bit values held in registers - currently we need an extra bit (well, 64 bits due to alignment) of information for implementing the NOTHINGness.)

**Comment by tethal** [comment]
Related to #187

**Comment by davidnich** [comment]
this will be done with the `%strict-types` parse directive
