### ISSUE TITLE
CI setup

### ISSUE THREAD

**Issue by tethal** [qorelanguage/qore#49]
Fix Jenkins setup, as a minimum:
 - make Jenkins run tests and set the status of the build accordingly
 - let Jenkins publish the status to GitHub
 - make Jenkins build all branches

Additional features would be nice but are not critical:
 - replace SCM polling with triggers (should be trivial)
 - show test result statistics - will require conversion of test output to a format understood by any of Jenkins' plugins, but there is already some support for this (--format=junit)
 - other cleanup of the configuration (e.g. mail notifications, build dependent projects)

**Comment by omusil24** [comment]
Jenkins now builds all branches of Qore and runs tests after building.  Branch 0.8.11.1 is installed into a separate directory and modules are then built with corresponding "old" branch and built against this separate installation of Qore.

Qore and all module builds are now triggered by Github when someone commits and build statuses are sent back to Github.
