### ISSUE TITLE
Documentation of escape characters in strings

### ISSUE THREAD

**Issue by tethal** [qorelanguage/qore#50]
According to the [documentation](http://qore.org/manual/current/lang/html/basic_data_types.html#string), the single quote character `'` can be escaped in a single-qouted string (`'hello \'there\''`).

**Code:**

```
print('hello \'there\'');
```

**Result:**

```
unhandled QORE System exception thrown in TID 1 at 2015-10-12 11:03:07.681628 Mon +02:00 (CEST) at t.q:1
PARSE-EXCEPTION: syntax error, unexpected identifier, expecting ')'
```

**Notes:**
- the regular expression in scanner.lpp does not implement this - the quoted string consists of everything except single quote, including backslash and newline:
  
  ```
  print('
  \a\
  
  ');
  ```
  
  prints `\a\` with an empty line before and after.
- if a single quote character should be escaped using a backslash, then backslash should be escapable as well
- the [documentation](http://qore.org/manual/current/lang/html/group__string__functions.html#string_escape_chars) for escapes in double-quoted strings does not mention that any character after a backslash except n, r, t, b, f, v and 0-7 is reproduced literally (including newline, backslash itself and digits 8 and 9)
- the sequence `\v` in double-quoted string is not documented
- the parser silently accepts escape sequences `\400` through `\777` (ignores overflow and uses the lower eight bits)

**Comment by davidnich** [comment]
fix docs please
- single-quoted strings: no escaping; multi-line OK
- double-quoted: please fix docs as above (including \v which is valid and cool! :))
- \400 - \700: please throw an error
