### ISSUE TITLE
the documentation for binary literals is incomplete

### ISSUE THREAD

**Issue by davidnich** [qorelanguage/qore#505]
binary literals are given in between angle brackets as an even series of hex digits - this is not properly documented

**Comment by gamato** [comment]
Right, it's not properly documented.

Besides, the following parse error is confusing, IMO, it should suggest there's a problem with the format, not usage of '<' itself.

```
$ qore -X '<09>'
binary object 0x7ffae97201a0 (1 byte)

$ qore -X '<9>'
unhandled QORE System exception thrown in TID 1 at 2016-02-07 14:54:44.620797 Sun +01:00 (CET) at <command-line>:2
PARSE-EXCEPTION: syntax error, unexpected '<', expecting variable reference or namespace-scoped global variable reference
```
