### ISSUE TITLE
groupby option does not allow numbers instead of column names

### ISSUE THREAD

**Issue by gamato** [qorelanguage/qore#510]
GROUP BY does not allow numbers, as is possible in SQL:

```
        soh = ("columns": (
                cop_as ("char_f", "pivot"),
                cop_as (cop_min ("id"), "cop_min"),
                ),
                "groupby": (1,)#("char_f"),
                );
```

OPTION-ERROR: pgsql_test: key "groupby" element 0/1 (first is 0) has type "integer", expecting "string" or "hash" (value: [1])

SQL example:

```
# select 123 as pivot, count(*) group by 1;
pivot │ count 
───────┼───────
 123 │     1
(1 row)
```

**Comment by gamato** [comment]
Test available in branch https://github.com/qorelanguage/qore/tree/feature/sqlutil_groupby

**Comment by davidnich** [comment]
not standard SQL but now supported in SqlUtil
