### ISSUE TITLE
recursive closures cause a memory leak

### ISSUE THREAD

**Issue by davidnich** [qorelanguage/qore#527]
ex:

<pre>
#!/usr/bin/env qore

%new-style
%enable-all-warnings
%require-types
%strict-args

main();

sub main() {
    code c = int sub (int i) {
        if (i == 1)
            return 1;
        return i * c(i - 1);
    };
}
</pre>

note that the closure does not have to be called - valgrind output:

<pre>
=13160== LEAK SUMMARY:
==13160==    definitely lost: 192 bytes in 1 blocks
==13160==    indirectly lost: 416 bytes in 4 blocks
==13160==      possibly lost: 0 bytes in 0 blocks
==13160==    still reachable: 1,038,986 bytes in 13,681 blocks
==13160==                       of which reachable via heuristic:
==13160==                         newarray           : 24 bytes in 1 blocks
==13160==         suppressed: 0 bytes in 0 blocks
</pre>

**Comment by omusil24** [comment]
Just FYI: mapper.qtest is still leaking. Not sure if it's the same problem.
