### ISSUE TITLE
hash update operators behave differently

### ISSUE THREAD

**Issue by gamato** [qorelanguage/qore#582]
Test source file:

```
$ cat petr.q
%new-style
*hash h1;
*hash h2;
h1 = h1 + h2;
h1 += h2;
```

While the first addition works, the latter fails (the order does not matter):

```
$ qore petr.q 
unhandled QORE System exception thrown in TID 1 at 2016-03-08 12:52:18.256086 Tue +01:00 (CET) at petr.q:5
RUNTIME-TYPE-ERROR: <lvalue> expects type '*hash', but got type 'int' instead
```

Also, I'm not sure why it's cast to `int`, anyway.

Btw, the following surprisingly works:

```
$ qore -ne '*hash h1; hash h2; printf("%n\n%n\n", h1, h2); h1+=h2;'
<NOTHING>
<NOTHING>
$
```

**Comment by davidnich** [comment]
@tethal can you take care of this please?  We can discuss at our c++ meeting @ 10am today

**Comment by tethal** [comment]
There actually seem to be two issues here:
1. the `+=` operator converts NOTHING to integer:
   
   ```
   %new-style
   
   *hash h1;
   *hash h2;
   printf("%s: %N\n", h1.type(), h1);
   h1 += h2;
   printf("%s: %N\n", h1.type(), h1);
   ```
   
   produces:
   
   ```
   nothing: <NOTHING>
   integer: 0
   ```
   
   Which is clearly incorrect, but should be easy to fix.
2. the second issue seems to be the way assignment of NOTHING is handled - it somehow changes the variable, even though the original and new values are both NOTHING. The example in the description above can be even reduced to assigning NOTHING directly:
   
   ```
   %new-style
   *hash h1;
   *hash h2;
   h1 = NOTHING;
   h1 += h2;
   
   unhandled QORE System exception thrown in TID 1 at 2016-03-09 10:56:50.708745 Wed Z (UTC) at t.q:5
   RUNTIME-TYPE-ERROR: <lvalue> expects type '*hash', but got type 'int' instead
   ```

Moreover, both issues affects other types as well, e.g. `*string`, `*list`, `*date` and even `*int`, `*float` and `*number`.

So the order actually does matter: 
- if you do `h1 += h2` first, then `h1` actually becomes an integer (issue 1) which the second operation `h1 = h1 + h2` correctly refuses, but with a slightly different error message:
  
  ```
  unhandled QORE System exception thrown in TID 1 at 2016-03-09 11:59:22.882385 Wed Z (UTC) at t.q:6
  RUNTIME-TYPE-ERROR: <lvalue> expects type '*hash', but got type 'integer' instead
  ```
- if you do `h1 = h1 + h2` first, it correctly produces NOTHING, but somehow changes h1 (issue 2) so the second operation `h1 += h2` fails for an unknown reason
