### ISSUE TITLE
Local variable can have the same name as an argument

### ISSUE THREAD

**Issue by tethal** [qorelanguage/qore#61]
**Code:**

    sub x(hash h) {
        printf("%N\n", h);
        hash h;
        printf("%N\n", h);
    }

    x(("a": 123));

**Output:**

    hash: (1 member)
      a : 123
    <NOTHING>

**Expected output:**
Parse error.

**Version:**    

    QORE for Linux x86_64 (64-bit build), Copyright (C) 2003 - 2015 David Nichols
    version 0.8.12 (builtin features: sql, threads, DGC, debug)
      git hash: fa33179ecb42652e5efee452ba15a816cce15b7b

**Comment by davidnich** [comment]
there is a warning for this:

```
david@quasar:~/src/qore/git/qore/qlib$ qore -wduplicate-local-vars -ne 'sub s(int t) { int t = 1; delete t;}'
warning encountered at <command-line>:1
DUPLICATE-LOCAL-VARIABLE: local variable 't' was already declared in this lexical scope at <command-line>:1
```
