### ISSUE TITLE
trim operator returns int?

### ISSUE THREAD

**Issue by alachata-qore** [qorelanguage/qore#62]
qore -ne 'string str = "123\n"; string l = trim str;'
unhandled QORE System exception thrown in TID 1 at 2015-10-26 15:38:46.719271 Mon +01:00 (CET) at <command-line>:1
PARSE-TYPE-ERROR: lvalue for assignment operator (=) expects type 'string', but right-hand side is type 'int'

**Comment by davidnich** [comment]
fixed in 27440da
