### ISSUE TITLE
date representation in yaml format a.k.a. %y string formatting

### ISSUE THREAD

**Issue by gamato** [qorelanguage/qore#623]
Hi, I don't think this is a valid YAML:

```
$ qore -ne 'hash h = ("d": now()); printf("%y\n", h);'
{d: 2016-03-16 11:02:00.000000 Wed +01:00 (CET)}
```

At least I'm not able to find any official examples having something like "Wed" and "(CET)".

**Comment by omusil24** [comment]
From the documentation:

> Any Qore value, formatted as a pseudo-YAML string, without any line breaks; this format option is similar to "%n", but uses a YAML-like format. Note that the output is not guaranteed to be parsed by the yaml module's parseYAML() function; it is for display purposes only; to get real YAML functionality, use the yaml module.

i.e. it's not supposed to be a valid YAML.

**Comment by gamato** [comment]
OK, understood.
