### ISSUE TITLE
there is a memory leak when assigning a closure that captures "self" to an object member

### ISSUE THREAD

**Issue by davidnich** [qorelanguage/qore#73]
ex:

<pre>
class A {
    public {
        any f = sub() {
            return self;
        };
    }
    destructor() {
        print("destroyed\n");
    }
}

A a();
</pre>

this issue was split from #37

**Comment by tethal** [comment]
Is this still an issue? I did not manage to reproduce it with current build.

**Comment by davidnich** [comment]
no this was fixed with the DGC development
