### ISSUE TITLE
SqlUtil: add new operator "substring"

### ISSUE THREAD

**Issue by gamato** [qorelanguage/qore#801]

**Comment by gamato** [comment]
@pvanek @davidnich -- Would you prefer cop_substr or cop_substring ?
The former matches how it's called in Qore, while the latter matches SQL usage.
Actually, it's substring() in SQL standard and all DBs (we support) other than Oracle.

**Comment by davidnich** [comment]
@gamato I don't care - you and Petr please decide

**Comment by gamato** [comment]
Implemented as part of #810
