### ISSUE TITLE
Windows timezone format problem

### ISSUE THREAD

**Issue by omusil24** [qorelanguage/qore#811]
There's something wrong with Qore and Windows timezone format. Happens at least on Win 7 and Win 10. Minimal Qorus program to trigger the problem:

```
#!/usr/bin/env qore

%new-style
%strict-args
%require-types
%enable-all-warnings

%requires QorusClientCore

QorusClient::init();
omqclient.initSystemDatasources(True);
Datasource db = omq.copy();
db.open();
```

Output:

```
unhandled QORE System exception thrown in TID 1 at 2016-05-02 14:06:57.705271 Mon +02:00 (Central Europe Daylight Time) in Datasource::open() (./bin/min.q:13, builtin code)
TZINFO-ERROR: error opening windows registry key 'SOFTWARE\Microsoft\Windows NT\CurrentVersion\Time Zones\(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague': The system cannot find the file specified.
call stack:
  1: Datasource::open() (./bin/min.q:13, builtin code)
```

**Comment by tethal** [comment]
Seems like Qorus is trying to use display name instead of registry key name - see https://qore.org/manual/develop/lang/html/time_zones.html for description of the difference.

**Comment by davidnich** [comment]
I think I found the source of the problem - the Datasource calls that are failing are failing with a string returned by AbstractDatasource::getConfigString() such as the following:

```
mysql:omquser/omquser@omquser(utf8)%xbox{optimal-numbers,timezone=(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague}
```

Here the wrong timezone value is being returned.
