### ISSUE TITLE
is_writable does not return correct value in all cases (effective vs. all groups list)

### ISSUE THREAD

**Issue by pvanek** [qorelanguage/qore#852]
lib/ql_file.qpp, function:
static bool is_writable_intern(const QoreStringNode\* path) {

already noted:

```
   // does not cover situations like:
   // $ id
   // uid=5920(user1) gid=6183(group1) groups=6003(group2),6183(group3)
   // $ ls -la /foo/bar/
   // drwxrwsr-x 2  5921 group2 4096 Aug  7 14:37 .
   // where 6183(group1) is an effective group etc so geteuid() != dir group
```

maybe to use getgroups as an addon?
int getgroups(int size, gid_t list[]);

**Comment by gamato** [comment]
It seems that checking getegid() against values from getgroups() would suffice.
This would still not cover ACLs that may be attached to a file (directory entry).
There seems to be other option -- faccessat(2) -- thought it has its own issues.
So maybe the safest way is actually to try to open the file and see if it works.

**Comment by pvanek** [comment]
another option to consider: http://linux.die.net/man/2/access

**Comment by gamato** [comment]
Yes, though access(2) seems to have a few issues. But, most importantly, it does not check using effective IDs.

**Comment by omusil24** [comment]
For effective IDs there's eaccess(3): http://linux.die.net/man/3/eaccess

**Comment by gamato** [comment]
"These functions are nonstandard."
faccessat(2) seems to be the best option.
But, as also suggested in the man page you linked, "Generally, it is safer just to attempt the desired operation and handle any permission error that occurs."

**Comment by davidnich** [comment]
please note that `access(2)` was removed from UNIX builds on Qore due to this note in the linux man page:

```
CAVEAT
     access() is a potential security hole and should never be used.
```

from the FreeBSD man page:

```
SECURITY CONSIDERATIONS
     The access() system call is a potential security hole due to race condi-
     tions and should never be used.  Set-user-ID and set-group-ID applica-
     tions should restore the effective user or group ID, and perform actions
     directly rather than use access() to simulate access checks for the real
     user or group ID.  The eaccess() system call likewise may be subject to
     races if used inappropriately.

     access() remains useful for providing clues to users as to whether opera-
     tions make sense for particular filesystem objects (e.g. 'delete' menu
     item only highlighted in a writable folder ... avoiding interpretation of
     the st_mode bits that the application might not understand -- e.g. in the
     case of AFS).  It also allows a cheaper file existence test than stat(2).
```

note that these comments also apply to fsaccessat(2) since they are basically equivalent to access(2).  I guess we should change this to just open the file in write mode and return true or false based on that result...

**Comment by pvanek** [comment]
the same situation in: q_path_is_readable

@omusil24 can you take this one, please? Actually it's affecting Rossini project (all Qorus 3.1 instances which are using filesystem user connection in H3G setup - we have to "chmod 777" toplevel directories on shared filesystems)

**Comment by gamato** [comment]
David, you're right, that's exactly one of issues I meant.
On the other hand, this is important for system code but not for user level Qore code, imo.  As user level code using is_writable() and then some operation always leaves room for races.  I'm not sure if that's of any importance though.

**Comment by gamato** [comment]
Also, faccessat(2) is considered to be safer than access(2).

**Comment by omusil24** [comment]
IMO all of the considered methods are susceptible to the problem described on the access(2) manpage.

**Comment by gamato** [comment]
Btw, using mktemp(3) would be better than hardcoding a test file name.
