### ISSUE TITLE
API for stream I/O

### ISSUE THREAD

**Issue by tethal** [qorelanguage/qore#869]

**Comment by tethal** [comment]
Todo:
- [x] add a mode parameter to FileOutputStream constructor
- [x] add streams for stdin, stdout and stderr
- [X] add StringOutputStream
- [X] add getEncoding to StringInputStream
- [x] remove Qore::dump()

**Comment by davidnich** [comment]
Todo:
- [ ] fix #1466 - which will also add input stream receiving support to the HTTPClient class
