### ISSUE TITLE
"synchronized" is not implemented properly for class methods

### ISSUE THREAD

**Issue by davidnich** [qorelanguage/qore#894]
class methods should be synchronized on their object, and not globally

additionally, synchronized closures probably should be synchronized on the closure itself and not globally

**Comment by tethal** [comment]
Also, two methods on the same object should use the same mutex (associated with the instance) and two static methods of the same class should share a mutex associated with the class. This way, synchronized would work as in Java and like [MethodImpl(MethodImplOptions.Synchronized)] in .NET.
