### ISSUE TITLE
Negative infinity support in Qore

### ISSUE THREAD

**Issue by gamato** [qorelanguage/qore#910]
While the underlying library routines correctly returns negative infinity values, there's no special constant support in parser and no special method of float and number types (such as infp() for positive infinity).

Example:

```
$ qore -X 'pow(-10.0, 1001)'
-inf
```

Please add parser support as well as a new method to test floats and numbers for negative infinity.

**Comment by gamato** [comment]
Thinking about it again, maybe Qore does not need a new special method for testing negative infinity, maybe `infp()` should return True for both positive and negative infinity, but a new constant (`@NInf@` ?) is definitely needed.

**Comment by tethal** [comment]
Is there a problem with `-@INF@`? I tried this:

```
otethal@floyd:~/src/qore/git/qore$ q -nX "-1.0e1000/1e-100 == -@INF@"
True
otethal@floyd:~/src/qore/git/qore$ q -nX "pow(-10.0, 1001)  == -@INF@"
True
```

And that seems OK to me.

**Comment by gamato** [comment]
Well, if that's how it's supposed to work, then okey.
I thought there should be a dedicated constant.
And I wasn't even aware that these constants are case insensitive. Btw why?

**Comment by tethal** [comment]
Yes, that is how it is supposed to work. I have no idea why are they case insensitive.

**Comment by gamato** [comment]
Hmm.. it does not seem to work in some scenarios:

```
$ qore -X 'nlog(number(@inf@))'
@Inf@
$ qore -X 'nlog(number(@inf@)).infp()'
True
$ qore -X 'nlog(number(@inf@)).nanp()'
False
$ qore -X 'nlog(number(@inf@)) == @inf@'
True
$ qore -X 'nlog(number(@inf@)) == @nan@' # this one is wrong
True
```

**Comment by tethal** [comment]
OK, what I meant is that you should be able to use `-@inf@` for negative infinity. Of course, the comparison of `@nan@` to anything should be false and this is a bug #915

**Comment by gamato** [comment]
What I meant is that it should not be True in that specific case (`@inf@ != @nan@`), but I think it should work in another specific case (`@nan@ == @nan@`).

**Comment by tethal** [comment]
AFAIK NAN is unordered - in fact, some implementations of is_nan look like this:

```
bool is_nan(x) { reutrn x != x; }
```

BTW: you can use the `n` suffix for the `@inf@` and `@nan@` constants as well:

```
otethal@floyd:~/src/qore/git/qore$ q -nX '@nan@n.type()'
"number"
otethal@floyd:~/src/qore/git/qore$ q -nX '@nan@.type()'
"float"
```

**Comment by omusil24** [comment]
According to the IEEE 754 (ftp://ftp.openwatcom.org/pub/devel/docs/ieee-754.pdf) part 5.7 Comparison:

> It shall be possible to compare floating-point numbers in all supported formats, even if the operands' formats differ. Comparisons are exact and never overflow nor underflow. Four mutually exclusive relations are possible: less than, equal, greater than, and unordered. The last case arises when at least one operand is NaN. Every NaN shall compare unordered with everything, including itself. Comparisons shall ignore the sign of zero (so +0= –0).
> 
> The result of a comparison shall be delivered in one of two ways at the implementor's option: either as a condition code identifying one of the four relations listed above, or as a true-false response to a predicate that names the specific comparison desired. In addition to the true-false response, an invalid operation exception (7.1) shall be signaled when, as indicated in Table 4, last column, unordered operands are compared using one of the predicates involving < or > but not ? (Here the symbol ? signifies unordered).

Table 4 then "says" that for ==, <, >, <=, >=, <=>, unordered means False.

**Comment by gamato** [comment]
OK, then we definitely need `nanp()` for floats, as requested in #909.
