### ISSUE TITLE
sort_descending_stable() reverses elements even when unnecessary

### ISSUE THREAD

**Issue by gamato** [qorelanguage/qore#940]
Qore has 4 different functions for sorting:
- sort
- sort_stable
- sort_descending
- sort_descending_stable

But what exactly does "stable" mean ?

I assumed it would not change original order of elements if unnecessary.
But it seems that `sort_descending_stable` reverses order of items even when there's no need (they have same "value").
Here's an example code:

```
        list x;
        list s;
        x = map ($1, 1), range(1,9);
        printf ("X:  %y\n", x);
        code f = int sub (list l, list r) { return l[1] <=> r[1]; };
        s = sort (x, f);
        printf ("S1: %y\n", s);
        s = sort_stable (x, f);
        printf ("S2: %y\n", s);
        s = sort_descending (x, f);
        printf ("S3: %y\n", s);
        s = sort_descending_stable (x, f);
        printf ("S4: %y\n", s);
```

And here's its output:

```
X:  [[1, 1], [2, 1], [3, 1], [4, 1], [5, 1], [6, 1], [7, 1], [8, 1], [9, 1]]
S1: [[1, 1], [2, 1], [3, 1], [4, 1], [5, 1], [6, 1], [7, 1], [8, 1], [9, 1]]
S2: [[1, 1], [2, 1], [3, 1], [4, 1], [5, 1], [6, 1], [7, 1], [8, 1], [9, 1]]
S3: [[7, 1], [6, 1], [9, 1], [8, 1], [1, 1], [3, 1], [2, 1], [5, 1], [4, 1]]
S4: [[9, 1], [8, 1], [7, 1], [6, 1], [5, 1], [4, 1], [3, 1], [2, 1], [1, 1]]
```

**Comment by tethal** [comment]
It is a bug, QoreListNode.cpp:551:

```
      if ((ascending && rc <= 0)
      || (!ascending && rc > 0))
```

should be 

```
      if ((ascending && rc <= 0)
      || (!ascending && rc >= 0))
```

**Comment by tethal** [comment]
Actually, there is a test in vars/array.qtest that tests for the current behavior, so it may have been intentional that the order is stable but reversed
@davidnich ?

**Comment by davidnich** [comment]
I really don't remember - nothing that I know relies on this behavior so we can change it if the current behavior is not logical / standard / etc

**Comment by tethal** [comment]
OK, thanks. 
I looked at Java, C++, Python and Perl. Java, C++ and Perl do not seem to support descending sort (you have to provide custom comparator) which means that they keep the original order. Python has a `reverse` argument to `sort()` and it also keeps the original order. So I would say that we should change it. Current behavior can be simulated by reverse(sort_stable()), though it won't be as efficient.

**Comment by gamato** [comment]
OK, I agree, too. Thanks.
