### ISSUE TITLE
memberGate non-inheritance is not well documented

### ISSUE THREAD

**Issue by tmandys** [qorelanguage/qore#945]
```
class foo {
    constructor() {
    }
    any memberGate(string member) {
        return sprintf("MEMBER: %s", member);
    }
}

class bar inherits public foo {
    constructor(hash h): foo(h) {
    }
}
foo i1();
printf("foo.wanted: %s\n", i1.wanted);

bar i2();
printf("bar.wanted: %s\n", i2.wanted);

```

> PARSE-EXCEPTION: member 'wanted' of class 'bar' referenced has no type information because it was not declared in a public or private member list, but parse options require type information for all declarations

**Comment by davidnich** [comment]
this is documented in several places - if the documentation is not clear then please raise a documentation bug with details about how it should be improved

**Comment by tmandys** [comment]
I cannot see it at 
https://qore.org/manual/develop/lang/html/qore_classes.html#class_members.

But if it's the feature then makes no sense using /memberGate/ in any 
abstract class as e.g. /AbstractCsvIterator. /Every non-abstract 
descendant class must implement /memberGate()/ by itself via copy&paste.

Dne 2.6.2016 v 09:03 David Nichols napsal(a):

> this is documented in several places - if the documentation is not 
> clear then please raise a documentation bug with details about how it 
> should be improved
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> https://github.com/qorelanguage/qore/issues/945#issuecomment-223211939, 
> or mute the thread 
> https://github.com/notifications/unsubscribe/AJ3Bp9pecMMVgoIP2o3FKReYukOv5tXEks5qHoA1gaJpZM4IsQms.

## 

Tomas Mandys
Qore Technologies
Email: tomas.mandys@qoretechnologies.com
Tel: +420-604690589
Skype: tmandys@hotmail.com

**Comment by davidnich** [comment]
ok I changed this to a documentation bug

yes, you are right, it makes no sense to implement it in an abstract class unless it's meant to be a helper method to be called by child classes; ex:

```
class Child inherits Parent {
    memberGate(string mem) {
        return Parent::memberGate(mem);
    }
}
```

**Comment by tmandys** [comment]
Workaround to get it working:
```
class bar inherits public foo {
    constructor(): foo() {
    }
    any memberGate(string member) {
        return foo::memberGate(member);
    }
}

```
