### ISSUE TITLE
wrong behaviour of continue & break when used where they should not be

### ISSUE THREAD

**Issue by gamato** [qorelanguage/qore#976]
`continue` and `break` statements should be allowed only within specific statements (as documented).
If used in other places, Qore should emit either an error or at least a warning message.
Currently they seem to silently behave like `return` statement.
That is highly unexpected and error prone.

**Comment by tethal** [comment]
Example:

```
%new-style
%strict-args
%require-types
%enable-all-warnings

sub f(int i) {
    if (i == 0) {
        break;
    }
    printf("Not executed\n");
}

f(0);
```

**Comment by tmandys** [comment]
continue does not consider parent statement

```
    foreach hash mm in (mms) {
        foreach hash mmd in (mmds) {
            switch (mmd.type) {
                case 'R':
                case 'S':
                    break;
                default:
                    continue;   # ignored and continues @here 
            }
            # @here
       }
    }

```

**Comment by tethal** [comment]
Unfortunately, in a `switch` statement `continue` behaves exactly the same as `break`, which is not correct

**Comment by davidnich** [comment]
no known code depends on these bugs, we can fix this stuff without worrying about breaking anything

**Comment by pavelkveton** [comment]
if this fix would potentially break things, then the normal practice is:
- in Qore: implement a “%broken-loop-statement” parse option (PO_BROKEN_LOOP_STATEMENT) - or something like that - which gives the old behavior
- in Qorus: implement a “compat-broken-loop-statement” option which will cause the above parse option to be set in all Program contexts (this is very easy now - it’s all done in one place in lib/qorus.ql actually and takes effect in the server and client…)

in qorus, we have the corresponding issue https://bugs.qoretechnologies.com/issues/1401
