### ISSUE TITLE
remove bash as dependency for build?

### ISSUE THREAD

**Issue by 357r4bd** [qorelanguage/qore#986]
This is not a show stopper, but a very nice to have.

I am working on the FreeBSD port, and it seems that on a build on a fresh FreeBSD install (using poudriere to test the build), the build fails because bash is not available.  Is it possible to use the Bourne Shell `/bin/sh` in the shebang of the scripts rather than `/usr/bin/env bash` - and of course make any necessary adjustments to the script (which hopefully would be minimal)? and IIRC available on any *nix even as a symlink to bash?

The reason I am asking is that it seems that some may not like to install bash just because they want to install Qore.

Thanks!

**Comment by davidnich** [comment]
yes of course - no problem - the use of bash was just due to laziness for sure - how do you want to do this - as a fix to the 0.8.12 branch (that will also go to develop), or for the next release (0.8.13, so in develop only)?

**Comment by 357r4bd** [comment]
Thank you for the quick reply. I think that it's fine to just have this for 0.8.13.

**Comment by davidnich** [comment]
no, problem, thanks for the heads up!

**Comment by davidnich** [comment]
not working on real Bourne shell actually - reopened
