### ISSUE TITLE
use quotes to include /intern/ headers

### ISSUE THREAD

**Issue by pavelkveton** [qorelanguage/qore#993]
(moved from Qorus bug reporting system, opened originally by PetrV):

All the includes like:
# include <._/intern/._>

should be replaced by quotes:
# include "._/intern/._"

We should probably change it by a short script when we have time to do that....

**Comment by martin-zemek** [comment]
done by the following command:
`find . -type f -exec sed -i 's/^\#include <\(.*\)\/intern\/\(.*\)>/\#include "\1\/intern\/\2"/g' {} \;`
